// Copyright (C) 2026 Mathieu Dutour Sikiric <mathieu.dutour@gmail.com>
#ifndef SRC_NON_LATTICE_PACKING_NONLATTICEPACKING_H_
#define SRC_NON_LATTICE_PACKING_NONLATTICEPACKING_H_

// clang-format off
#include "../src_delaunay/JointCoveringDouble.h"
// clang-format on

/*
  Local optimization of m-periodic sphere packings, following
  Andreanov--Kallus, "Locally optimal 2-periodic sphere packings",
  Discrete Comput. Geom. (2019), and Schuermann's local theory of
  periodic extremeness.

  The point set is X = Z^n + {c_1 = 0, c_2, ..., c_m} in the metric Q,
  the parametrization (Q, C) used throughout polyhedral_common. In the
  Andreanov--Kallus picture this is a chart of the rank-n variety
  R_0(lambda) inside the space of (n+m-1) x (n+m-1) forms

      J = [ Q   R^T ]         Q_ij = <a_i, a_j>,
          [ R   S   ]         R_ij = <b_i, a_j>,  S_ij = <b_i, b_j>,

  on which every squared inter-point distance J(k) = <k k^T, J>,
  k in M = Z^n x (E - E), is LINEAR.  The Ryshkov-like polyhedron
  R(lambda) = { J : J(k) >= lambda for k in M \ {0} } is a locally
  finite polyhedron and the packing problem is

      minimize det Q(J)  over  J in R(lambda), rank J = n.

  Working in the chart (Q, C) trades the linear structure of the
  constraints for an unconstrained parametrization: the rank condition
  holds identically, at the price that J(k) becomes quadratic in C.
  This file implements, in double precision:

  * the packing density and its shortest pair vectors
    (via ShortPairVectors / PackingMin2 of JointCoveringDouble.h);
  * DescendPacking: maximization of the packing density
      phi = V_n (lambda/2)^n m / sqrt(det Q)
    by staged-softmin L-BFGS on log phi, re-enumerating the short
    vectors as they change;
  * PackingCertify: the first-order extremeness test.  A configuration
    is a strict local maximum to first order iff no direction d in
    (Q, C)-space has  (n/2) (min_j g_j . d)/lambda^2 - (1/2) gdet . d > 0
    over the active gradients g_j of the squared pair norms -- the
    chart expression of Andreanov--Kallus algebraic extremeness
    (Definition 2.3), whose dual form is: the cone generated by the
    active k k^T plus the tangent-space annihilator contains the
    objective gradient G_J.  Solved with the same small dense simplex
    as the covering certificate, and, per the lesson learned there, the
    reported rate is recomputed from the returned direction, never
    trusted from the simplex objective.
  * a floating/fluid diagnostic: the dimension of the space of
    directions annihilating all active constraints to first order
    (Andreanov--Kallus fluid packings, e.g. the 9-dimensional fluid
    diamond, live in such flat directions; for m = 2 they are exactly
    the unions of two translates of an extreme lattice whose covering
    radius exceeds twice its packing radius).

  Everything here is search-and-certify in double precision; the exact
  enumeration of the vertices of R(lambda) (the generalized Voronoi
  algorithm of Andreanov--Kallus) is future work, see NOTES.md.
 */

namespace non_lattice_packing {

using namespace joint_covering_double;

// packing density phi = V_n (lambda/2)^n m / sqrt(det Q)
struct PackingResult {
  double phi;
  double lambda2;
  int n_short;   // pair vectors attaining ~lambda^2
};

inline PackingResult PackingDensity(PeriodicConfig const &conf,
                                    double act_tol = 1e-6) {
  double l2 = PackingMin2(conf.Q, conf.C);
  std::vector<ShortPair> pr =
      ShortPairVectors(conf.Q, conf.C, l2 * (1.0 + 10 * act_tol));
  double det = conf.Q.determinant();
  double rho = 0.5 * std::sqrt(l2);
  double phi = conf.m * VolumeUnitBall(conf.n) * std::pow(rho, conf.n) /
               std::sqrt(det);
  return {phi, l2, (int)pr.size()};
}

// F = -(n/2) log smin_beta(s^2) + (1/2) log det Q  (minimizing F maximizes
// the packing density), gradient in the packed (Cholesky L, cosets) chart.
inline double ObjectiveGradientPacking(Packing const &pk,
                                       std::vector<ShortPair> const &shorts,
                                       double beta, VectorXd const &x,
                                       VectorXd &grad) {
  int n = pk.n;
  MatrixXd Lo, C;
  Unpack(pk, x, Lo, C);
  MatrixXd Q = Lo * Lo.transpose();
  int n_sh = shorts.size();
  std::vector<double> S2(n_sh);
  std::vector<VectorXd> Wv(n_sh);
  double minS2 = 1e30;
  for (int j = 0; j < n_sh; j++) {
    VectorXd wv = shorts[j].v.cast<double>() + C.row(shorts[j].t).transpose() -
                  C.row(shorts[j].s).transpose();
    S2[j] = wv.dot(Q * wv);
    Wv[j] = std::move(wv);
    minS2 = std::min(minS2, S2[j]);
  }
  double Zm = 0;
  std::vector<double> vw(n_sh);
  for (int j = 0; j < n_sh; j++) {
    vw[j] = std::exp(-beta * (S2[j] - minS2));
    Zm += vw[j];
  }
  double smin = minS2 - std::log(Zm) / beta;
  for (int j = 0; j < n_sh; j++) vw[j] /= Zm;
  double logdet = 0;
  for (int i = 0; i < n; i++) {
    logdet += 2 * std::log(std::abs(Lo(i, i)) + 1e-300);
  }
  double F = -0.5 * n * std::log(std::max(smin, 1e-300)) + 0.5 * logdet;
  MatrixXd dFdQ = MatrixXd::Zero(n, n);
  MatrixXd dFdC = MatrixXd::Zero(pk.m, n);
  double c_in = 0.5 * n / std::max(smin, 1e-300);
  for (int j = 0; j < n_sh; j++) {
    double cw = c_in * vw[j];
    if (cw < 1e-16) continue;
    VectorXd const &wv = Wv[j];
    dFdQ -= cw * (wv * wv.transpose());
    if (shorts[j].t != shorts[j].s) {
      VectorXd qw = 2.0 * (Q * wv);
      dFdC.row(shorts[j].t) -= cw * qw.transpose();
      dFdC.row(shorts[j].s) += cw * qw.transpose();
    }
  }
  dFdQ = 0.5 * (dFdQ + dFdQ.transpose());
  MatrixXd gL = 2.0 * dFdQ * Lo;
  for (int i = 0; i < n; i++) {
    gL(i, i) += 1.0 / Lo(i, i);   // + (1/2) log det part
  }
  grad.resize(pk.dim());
  int pos = 0;
  for (int i = 0; i < n; i++) {
    for (int j = 0; j <= i; j++) {
      grad(pos++) = gL(i, j);
    }
  }
  for (int t = 1; t < pk.m; t++) {
    for (int j = 0; j < n; j++) {
      grad(pos++) = dFdC(t, j);
    }
  }
  return F;
}

// Local maximization of the packing density: enumerate the short pairs,
// staged-softmin L-BFGS on the frozen list, re-enumerate, repeat.
// DescendResult.theta carries the packing density phi (to MAXIMIZE, so the
// bookkeeping keeps the largest).
inline DescendResult DescendPacking(PeriodicConfig conf, int rounds,
                                    std::ostream &os, bool verbose = false) {
  Packing pk{conf.n, conf.m, conf.n * (conf.n + 1) / 2};
  DescendResult best;
  int stall = 0;
  for (int it = 0; it < rounds; it++) {
    PackingResult pr0;
    try {
      pr0 = PackingDensity(conf);
    } catch (std::runtime_error &e) {
      return best;
    }
    if (!best.success || pr0.phi > best.theta + 1e-12) {
      best.success = true;
      best.theta = pr0.phi;
      best.conf = conf;
    }
    conf.Q /= pr0.lambda2;   // normalize lambda^2 = 1
    // wrap the cosets into [0,1)^n (a pure Z^n shift, changing nothing)
    for (int t = 1; t < conf.m; t++)
      for (int j = 0; j < conf.n; j++)
        conf.C(t, j) -= std::floor(conf.C(t, j));
    std::vector<ShortPair> shorts;
    try {
      shorts = ShortPairVectors(conf.Q, conf.C, 1.8);
    } catch (std::runtime_error &e) {
      return best;
    }
    Eigen::LLT<MatrixXd> llt(conf.Q);
    if (llt.info() != Eigen::Success) {
      return best;
    }
    MatrixXd Lo = llt.matrixL();
    VectorXd x = Pack(pk, Lo, conf.C);
    double beta = 200.0;
    for (int stage = 0; stage < 6; stage++) {
      auto f = [&](VectorXd const &xv, VectorXd &g) -> double {
        return ObjectiveGradientPacking(pk, shorts, beta, xv, g);
      };
      LBFGS(f, x, 150, 1e-10, os);
      beta *= 5.0;
      // the objective is scale invariant, so the parametrization drifts in
      // scale during the descent; pin tr Q = n between the beta stages
      {
        MatrixXd Lo2, C2;
        Unpack(pk, x, Lo2, C2);
        double tr = (Lo2 * Lo2.transpose()).trace();
        if (tr > 1e-300) {
          Lo2 *= std::sqrt(double(pk.n) / tr);
          x = Pack(pk, Lo2, C2);
        }
      }
    }
    MatrixXd C_new;
    Unpack(pk, x, Lo, C_new);
    conf.Q = Lo * Lo.transpose();
    conf.C = C_new;
    conf.C.row(0).setZero();
    PackingResult ver;
    try {
      ver = PackingDensity(conf);
    } catch (std::runtime_error &e) {
      return best;
    }
    best.n_retessellations = it + 1;
    if (verbose) {
      os << "  round " << it << ": verified phi = " << ver.phi
         << " (lambda2=" << ver.lambda2 << " short=" << ver.n_short << ")\n";
    }
    if (ver.phi > best.theta + 1e-12) {
      best.success = true;
      best.theta = ver.phi;
      best.conf = conf;
      stall = 0;
    } else {
      stall++;
      if (stall >= 2) return best;
    }
  }
  return best;
}

// First-order extremeness certificate.  In the chart, log phi changes to
// first order along d by  (n/2) (min over active j of g_j . d) / lambda^2
// - (1/2) gdet . d ; the configuration is extreme to first order iff the
// maximum of this over the box |d| <= rho is 0 (attained at d = 0).  LP over
// (d, s):  maximize (n/2)/lambda^2 s - (1/2) gdet . d  subject to
// g_j . d >= s (active j), -rho <= d <= rho -- the chart form of the
// algebraic-extremeness test of Andreanov--Kallus Definition 2.3.
struct PackingCertificate {
  double rate;       // best linearized increase of log phi per unit box
  int n_active;
  int grad_rank;     // rank of the active-gradient family (with gdet)
  int dim;           // dimension of the (Q, C) chart
  bool extreme;      // rate ~ 0: no first-order improvement
  int n_floating;    // dim of directions annihilating all active gradients
                     // and gdet: flat (fluid/floating) directions
};

inline PackingCertificate PackingCertify(PeriodicConfig const &conf,
                                         double act_tol = 1e-6,
                                         double rho = 1e-3) {
  int n = conf.n, m = conf.m;
  auto basis = SymBasis(n);
  int dQ = basis.size();
  int dim = dQ + n * (m - 1);
  double l2 = PackingMin2(conf.Q, conf.C);
  std::vector<ShortPair> pr =
      ShortPairVectors(conf.Q, conf.C, l2 * (1.0 + act_tol));
  // gradients of the squared pair norms in the chart
  int na = pr.size();
  std::vector<VectorXd> g(na, VectorXd::Zero(dim));
  for (int j = 0; j < na; j++) {
    VectorXd w = pr[j].v.cast<double>() + conf.C.row(pr[j].t).transpose() -
                 conf.C.row(pr[j].s).transpose();
    // d s^2 / dQ_kl
    for (int u = 0; u < dQ; u++) {
      int k = basis[u].first, l = basis[u].second;
      g[j](u) = (k == l) ? w(k) * w(k) : 2.0 * w(k) * w(l);
    }
    if (pr[j].t != pr[j].s) {
      VectorXd qw = 2.0 * (conf.Q * w);
      for (int i = 0; i < n; i++) {
        g[j](dQ + (pr[j].t - 1) * n + i) += qw(i);
      }
      if (pr[j].s != 0) {
        for (int i = 0; i < n; i++) {
          g[j](dQ + (pr[j].s - 1) * n + i) -= qw(i);
        }
      }
    }
  }
  // careful: coset 0 is pinned at the origin; the loops above already skip it
  VectorXd gdet = VectorXd::Zero(dim);
  MatrixXd Qinv = conf.Q.inverse();
  for (int u = 0; u < dQ; u++) {
    int k = basis[u].first, l = basis[u].second;
    gdet(u) = (k == l) ? Qinv(k, k) : 2.0 * Qinv(k, l);
  }
  // LP: variables dp, dn (split of d), sp, sn (split of s)
  int nvar = 2 * dim + 2;
  int idx_sp = 2 * dim, idx_sn = 2 * dim + 1;
  double Sbnd = 0;
  for (int j = 0; j < na; j++) {
    double l1 = 0;
    for (int k = 0; k < dim; k++) l1 += std::abs(g[j](k));
    Sbnd = std::max(Sbnd, rho * l1);
  }
  Sbnd = std::max(Sbnd, 1e-6) * 1.5;
  int ncon = na + 2 * dim + 2;
  MatrixXd A = MatrixXd::Zero(ncon, nvar);
  VectorXd b = VectorXd::Zero(ncon);
  int row = 0;
  for (int j = 0; j < na; j++) {
    // g_j . d >= s   <->   -g_j . d + s <= 0
    for (int k = 0; k < dim; k++) {
      A(row, k) = -g[j](k);
      A(row, dim + k) = g[j](k);
    }
    A(row, idx_sp) = 1.0;
    A(row, idx_sn) = -1.0;
    b(row) = 0.0;
    row++;
  }
  for (int k = 0; k < 2 * dim; k++) {
    A(row, k) = 1.0;
    b(row) = rho;
    row++;
  }
  A(row, idx_sp) = 1.0; b(row) = Sbnd; row++;
  A(row, idx_sn) = 1.0; b(row) = Sbnd; row++;
  double coef = 0.5 * n / l2;
  // maximize coef*s - (1/2) gdet.d  ->  minimize -coef*s + (1/2) gdet.d
  VectorXd c = VectorXd::Zero(nvar);
  for (int k = 0; k < dim; k++) {
    c(k) = 0.5 * gdet(k);
    c(dim + k) = -0.5 * gdet(k);
  }
  c(idx_sp) = -coef;
  c(idx_sn) = coef;
  LPResult lp = SimplexMin(c, A, b);
  VectorXd d = VectorXd::Zero(dim);
  if (lp.status == 0 || lp.status == 2) {
    for (int k = 0; k < dim; k++) d(k) = lp.x(k) - lp.x(dim + k);
  }
  // recompute the true first-order rate from the returned direction: this
  // LP is as degenerate as the covering one (every active row has zero
  // right-hand side) and the simplex objective cannot be trusted
  double s_real = 0.0;
  bool any = false;
  for (int j = 0; j < na; j++) {
    double gd = g[j].dot(d);
    if (!any || gd < s_real) { s_real = gd; any = true; }
  }
  double rate = any ? (coef * s_real - 0.5 * gdet.dot(d)) / rho : 0.0;
  if (rate < 0.0) rate = 0.0;
  // rank of the active gradients + gdet, and flat directions
  MatrixXd Gm(na + 1, dim);
  for (int j = 0; j < na; j++) Gm.row(j) = g[j].transpose();
  Gm.row(na) = gdet.transpose();
  Eigen::JacobiSVD<MatrixXd> svd(Gm);
  double smax_sv = svd.singularValues()(0);
  int rank = 0;
  for (int i = 0; i < svd.singularValues().size(); i++) {
    if (svd.singularValues()(i) > 1e-9 * smax_sv) rank++;
  }
  int n_floating = dim - rank;
  return {rate, na, rank, dim, rate < 1e-7, n_floating};
}

}  // namespace non_lattice_packing

#endif  // SRC_NON_LATTICE_PACKING_NONLATTICEPACKING_H_
