// Copyright (C) 2026 Mathieu Dutour Sikiric <mathieu.dutour@gmail.com>
#ifndef SRC_IGUSA_IGUSA_VERTEX_FACE_H_
#define SRC_IGUSA_IGUSA_VERTEX_FACE_H_

// clang-format off
#include "igusa_facet.h"
#include <string>
#include <vector>
// clang-format on

#ifdef DEBUG
#define DEBUG_IGUSA_VERTEX_FACE
#endif

#ifdef SANITY_CHECK
#define SANITY_CHECK_IGUSA_VERTEX_FACE
#endif

/*
  A rigorous test of whether A in I is a vertex of P = conv(I).

  The inequalities X[v] >= 1, for the vectors v with A[v] = 1, are valid on
  P and tight at A. So A lies on the face

      P_A = P cap E,   E = { X : X[v] = 1 for all v with A[v] = 1 },

  and A is a vertex of P if and only if it is a vertex of P_A. The face is
  of small dimension k: k = 0 for a perfect form. Its integral points are
  A + D with D in the lattice L_E = { D in L : D[v] = 0 }, of rank k, with
  basis K. Its recession cone is made of the positive semidefinite forms
  vanishing on the span W of the vectors v, that is the forms B^T M B with
  M positive semidefinite, B a basis of the linear forms vanishing on W.

  A is a vertex of P_A if and only if the cone generated by the D = X - A,
  X in P_A, and by the recession directions is pointed and A is exposed:
  there is a functional h with h(D) > 0 for all of them. The iteration:
  * S is a list of directions D = X - A of integral points X of the face
    and R a list of recession directions B^T w w^T B;
  * a linear program looks for h with h >= z on S and R, maximizing z with
    h in a box;
  * if z <= 0, there is lambda >= 0 with sum_S lambda_D D + sum_R mu_R R = 0
    and sum lambda_D = 1 (Farkas): A is the convex combination of the
    X_D = A + D minus a positive semidefinite form, so A is not a vertex
    (it is a midpoint if the semidefinite part is non zero). The lambda
    are computed by a second linear program and checked exactly;
  * if z > 0: h is first made positive definite on the recession cone (a
    vector w with M_h[w] <= 0 adds B^T w w^T B to R). Then h is minimized
    over the integral points of the face by integer programming. A point
    with h(X) < h(A) is added to S. If the minimum is h(A), the face
    { h = h(A) } of P_A is checked to be the point A by minimizing and
    maximizing the k coordinates of L_E over it; another point is added to
    S. Otherwise A is the unique minimizer of h on P_A: A is a vertex,
    exposed by h.
  Both answers come with a certificate (the functional h, or the convex
  combination). Each round adds a new integral point of the face.
 */

template <typename T> struct IgusaVertexTestResult {
  bool is_vertex;
  // dimension of the face P_A
  int dim_face;
  // rank of the span of the vectors of norm 1
  int rank_min;
  int n_iter;
  // For a vertex: the functional on the coordinates of the face
  MyVector<T> h;
  // For a non vertex: the points X_D and the weights
  std::vector<MyMatrix<T>> l_point;
  std::vector<T> l_weight;
  // A = sum_i weight_i point_i + remainder, the remainder positive
  // semidefinite
  MyMatrix<T> remainder;
};

// The face P_A of A: the equalities X[v] = 1, the lattice of its directions
// and its recession cone.
template <typename T, typename Tint> struct IgusaFaceData {
  MyVector<T> x_A;
  // the vectors v with A[v] = 1
  std::vector<MyVector<Tint>> l_v;
  // the equalities X[v] = 1, as rows (-1, X[v] coefficients)
  MyMatrix<T> Equa;
  // the rank of the span W of the v
  int rank_min;
  // K: a basis of L_E (rows, in the coordinates of the T-space), and N an
  // integral matrix with K N^T = I, so that t = N x_D for a direction x_D
  // in L_E. N exists since L_E is saturated; being integral it keeps the
  // coefficients of the functionals small (a least squares inverse
  // (K K^T)^{-1} K has large denominators, too large for SCIP).
  MyMatrix<T> K;
  MyMatrix<T> N;
  // the dimension of the face
  int k;
  // B: a basis of the linear forms vanishing on W (q rows); the recession
  // cone is { B^T M B : M positive semidefinite }
  int q;
  MyMatrix<T> B;
  // sum_v v v^T, the matrix of sum_v X[v]
  MyMatrix<T> Vsum;
};

template <typename T, typename Tint>
IgusaFaceData<T, Tint> igusa_face_data(IgusaSpace<T, Tint> const &space,
                                       MyMatrix<T> const &A,
                                       std::ostream &os) {
  int n = space.n;
  int dim = space.dim;
  IgusaFaceData<T, Tint> face;
  face.x_A = igusa_coordinates(space, A);
  for (auto &v : computeLevel_GramMat<T, Tint>(A, T(1), os)) {
    if (EvaluationQuadForm<T, Tint>(A, v) == T(1)) {
      face.l_v.push_back(v);
    }
  }
  int n_v = face.l_v.size();
  face.Equa = MyMatrix<T>(n_v, dim + 1);
  MyMatrix<T> Erows(n_v, dim);
  MyMatrix<T> V(n_v, n);
  face.Vsum = ZeroMatrix<T>(n, n);
  for (int i = 0; i < n_v; i++) {
    MyVector<Tint> const &v = face.l_v[i];
    face.Equa(i, 0) = T(-1);
    for (int j = 0; j < dim; j++) {
      T val = EvaluationQuadForm<T, Tint>(space.ListMatInt[j], v);
      face.Equa(i, j + 1) = val;
      Erows(i, j) = val;
    }
    for (int j = 0; j < n; j++) {
      V(i, j) = UniversalScalarConversion<T, Tint>(v(j));
    }
    for (int a = 0; a < n; a++) {
      for (int b = 0; b < n; b++) {
        face.Vsum(a, b) += UniversalScalarConversion<T, Tint>(v(a) * v(b));
      }
    }
  }
  face.rank_min = (n_v == 0) ? 0 : RankMat(V);
  face.K = (n_v == 0) ? IdentityMat<T>(dim) : NullspaceIntTrMat(Erows);
  face.k = face.K.rows();
  if (face.k > 0) {
    MyMatrix<Tint> Kt_int =
        UniversalMatrixConversion<Tint, T>(MyMatrix<T>(face.K.transpose()));
    face.N = MyMatrix<T>(face.k, dim);
    for (int i = 0; i < face.k; i++) {
      MyVector<Tint> e = ZeroVector<Tint>(face.k);
      e(i) = 1;
      std::optional<MyVector<Tint>> opt = SolutionIntMat(Kt_int, e);
      MyVector<Tint> y = unfold_opt(opt, "L_E is saturated");
      for (int j = 0; j < dim; j++) {
        face.N(i, j) = UniversalScalarConversion<T, Tint>(y(j));
      }
    }
  }
  face.q = n - face.rank_min;
  face.B = MyMatrix<T>(0, n);
  if (face.q > 0) {
    if (static_cast<int>(space.LinSpa.ListMat.size()) != n * (n + 1) / 2) {
      std::cerr << "IGUSA_VERTEX_FACE: an unbounded face is only treated for "
                   "the full space of symmetric matrices\n";
      throw TerminalException{1};
    }
    face.B = (n_v == 0) ? IdentityMat<T>(n) : NullspaceIntTrMat(V);
  }
  return face;
}

// The coordinates t in the basis K of a direction x_D of L_E
template <typename T, typename Tint>
MyVector<T> igusa_face_coordinates(IgusaFaceData<T, Tint> const &face,
                                   MyVector<T> const &x_D) {
  return face.N * x_D;
}

// The coordinates of the recession direction B^T w w^T B
template <typename T, typename Tint>
MyVector<T>
igusa_face_recession_direction(IgusaSpace<T, Tint> const &space,
                               IgusaFaceData<T, Tint> const &face,
                               MyVector<T> const &w) {
  int n = space.n;
  MyVector<T> Bw = face.B.transpose() * w;
  MyMatrix<T> D(n, n);
  for (int i = 0; i < n; i++) {
    for (int j = 0; j < n; j++) {
      D(i, j) = Bw(i) * Bw(j);
    }
  }
  return igusa_face_coordinates(face, igusa_coordinates(space, D));
}

template <typename T> T igusa_dot(MyVector<T> const &a, MyVector<T> const &b) {
  T sum(0);
  for (int i = 0; i < a.size(); i++) {
    sum += a(i) * b(i);
  }
  return sum;
}

// The matrix Hq with c(B^T M B) = tr(Hq M) for M symmetric q x q
template <typename T, typename Tint>
MyMatrix<T> igusa_face_recession_matrix(IgusaSpace<T, Tint> const &space,
                                        IgusaFaceData<T, Tint> const &face,
                                        MyVector<T> const &c) {
  int q = face.q;
  auto unit = [&](int i) -> MyVector<T> {
    MyVector<T> w = ZeroVector<T>(q);
    w(i) = T(1);
    return w;
  };
  auto value = [&](MyVector<T> const &w) -> T {
    return igusa_dot(c, igusa_face_recession_direction(space, face, w));
  };
  MyMatrix<T> Hq(q, q);
  for (int i = 0; i < q; i++) {
    Hq(i, i) = value(unit(i));
    for (int j = i + 1; j < q; j++) {
      MyVector<T> wij = unit(i) + unit(j);
      T val = (value(wij) - value(unit(i)) - value(unit(j))) / T(2);
      Hq(i, j) = val;
      Hq(j, i) = val;
    }
  }
  return Hq;
}

// tr(A^{-1} X) on the face: positive on all the positive semidefinite
// directions, so coercive on the face, and well conditioned.
template <typename T, typename Tint>
MyVector<T> igusa_face_initial_functional(IgusaSpace<T, Tint> const &space,
                                          IgusaFaceData<T, Tint> const &face,
                                          MyMatrix<T> const &A) {
  int dim = space.dim;
  MyMatrix<T> Ainv = Inverse(A);
  MyVector<T> s_full(dim);
  for (int j = 0; j < dim; j++) {
    s_full(j) = frobenius_inner(Ainv, space.ListMatInt[j]);
  }
  return face.K * s_full;
}

// The directions found so far: those of integral points of the face (with
// the points) and the recession directions.
template <typename T> struct IgusaFaceDirections {
  std::vector<MyVector<T>> S_t;
  std::vector<MyMatrix<T>> S_X;
  std::vector<MyVector<T>> R_t;
};

/*
  The linear program in (c, z): maximize z subject to c.t >= z for all the
  directions t, with c in the box [-1,1]^k and z <= 1. Returns c if z > 0,
  and none otherwise.
 */
template <typename T, typename Tint>
std::optional<MyVector<T>>
igusa_face_separation(IgusaFaceData<T, Tint> const &face,
                      IgusaFaceDirections<T> const &dirs, std::ostream &os) {
  int k = face.k;
  int n_s = dirs.S_t.size();
  int n_r = dirs.R_t.size();
  int n_var = k + 1;
  MyMatrix<T> Ineq = ZeroMatrix<T>(n_s + n_r + 2 * k + 1, n_var + 1);
  int row = 0;
  auto add_dir = [&](MyVector<T> const &t) -> void {
    for (int i = 0; i < k; i++) {
      Ineq(row, 1 + i) = t(i);
    }
    Ineq(row, 1 + k) = T(-1);
    row++;
  };
  for (auto &t : dirs.S_t) {
    add_dir(t);
  }
  for (auto &t : dirs.R_t) {
    add_dir(t);
  }
  for (int i = 0; i < k; i++) {
    for (int sign = -1; sign <= 1; sign += 2) {
      Ineq(row, 0) = T(1);
      Ineq(row, 1 + i) = T(sign);
      row++;
    }
  }
  Ineq(row, 0) = T(1);
  Ineq(row, 1 + k) = T(-1);
  MyVector<T> obj = ZeroVector<T>(n_var + 1);
  obj(1 + k) = T(-1);
  LpSolution<T> sol = SIMPLEX_LinearProgramming(Ineq, obj, os);
  MyVector<T> cz = unfold_opt(sol.DirectSolution, "The box LP");
  if (cz(k) <= 0) {
    return {};
  }
  MyVector<T> c(k);
  for (int i = 0; i < k; i++) {
    c(i) = cz(i);
  }
  return c;
}

/*
  When no separating functional exists: lambda, mu >= 0 with sum lambda = 1
  and sum lambda t_D + sum mu t_R = 0, by a linear program. Then
  A = sum lambda X_D + (positive semidefinite remainder), checked exactly.
 */
template <typename T, typename Tint>
void igusa_face_convex_combination(IgusaFaceData<T, Tint> const &face,
                                   IgusaFaceDirections<T> const &dirs,
                                   MyMatrix<T> const &A,
                                   IgusaVertexTestResult<T> &result,
                                   std::ostream &os) {
  int k = face.k;
  int n = A.rows();
  int n_s = dirs.S_t.size();
  int n_r = dirs.R_t.size();
  int n_lm = n_s + n_r;
  MyMatrix<T> Ineq = ZeroMatrix<T>(n_lm + 2 * k + 2, n_lm + 1);
  int row = 0;
  for (int i = 0; i < n_lm; i++) {
    Ineq(row, 1 + i) = T(1);
    row++;
  }
  for (int i = 0; i < k; i++) {
    for (int sign = -1; sign <= 1; sign += 2) {
      for (int a = 0; a < n_s; a++) {
        Ineq(row, 1 + a) = T(sign) * dirs.S_t[a](i);
      }
      for (int b = 0; b < n_r; b++) {
        Ineq(row, 1 + n_s + b) = T(sign) * dirs.R_t[b](i);
      }
      row++;
    }
  }
  for (int sign = -1; sign <= 1; sign += 2) {
    Ineq(row, 0) = T(-sign);
    for (int a = 0; a < n_s; a++) {
      Ineq(row, 1 + a) = T(sign);
    }
    row++;
  }
  MyVector<T> obj = ZeroVector<T>(n_lm + 1);
  LpSolution<T> sol = SIMPLEX_LinearProgramming(Ineq, obj, os);
  MyVector<T> lm =
      unfold_opt(sol.DirectSolution, "The convex combination certificate");
  MyMatrix<T> Sum = ZeroMatrix<T>(n, n);
  for (int a = 0; a < n_s; a++) {
    if (lm(a) > 0) {
      result.l_point.push_back(dirs.S_X[a]);
      result.l_weight.push_back(lm(a));
      Sum += lm(a) * dirs.S_X[a];
    }
  }
  MyMatrix<T> Rem = A - Sum;
  if (!IsPositiveSemiDefinite(Rem, os)) {
    std::cerr << "IGUSA_VERTEX_FACE: the certificate is not valid\n";
    throw TerminalException{1};
  }
  result.remainder = Rem;
}

/*
  The function f on the coordinates of the T-space that is c.t on the face.
  On the face it can be changed by multiples of X[v] - 1: with
  f + lambda sum_v (X[v] - 1), of matrix M_f + lambda sum_v v v^T, positive
  definite for lambda large since M_f is positive definite on the recession
  cone, the integer programs are coercive on the whole space, and the cuts
  are seeded with the short vectors of the inverse of that matrix.
 */
template <typename T, typename Tint>
MyVector<T> igusa_face_coercive_function(IgusaSpace<T, Tint> &space,
                                         IgusaFaceData<T, Tint> const &face,
                                         MyVector<T> const &c,
                                         std::ostream &os) {
  int dim = space.dim;
  MyVector<T> f_lin = face.N.transpose() * c;
  MyVector<T> f(dim + 1);
  f(0) = T(0);
  for (int j = 0; j < dim; j++) {
    f(j + 1) = f_lin(j);
  }
  if (face.l_v.empty()) {
    return f;
  }
  MyVector<T> y = Inverse(space.TraceGram) * f_lin;
  MyMatrix<T> Mf = igusa_matrix(space, y);
  T lambda(0);
  for (int iter = 0; iter < 60; iter++) {
    if (IsPositiveDefinite(MyMatrix<T>(Mf + lambda * face.Vsum), os)) {
      break;
    }
    lambda = (lambda == 0) ? T(1) : T(2) * lambda;
  }
  for (int i = 0; i < face.Equa.rows(); i++) {
    for (int j = 0; j <= dim; j++) {
      f(j) += lambda * face.Equa(i, j);
    }
  }
  MyMatrix<T> Mlambda = Mf + lambda * face.Vsum;
  if (IsPositiveDefinite(Mlambda, os)) {
    igusa_insert_seed_cuts(space, Mlambda, os);
  }
  return f;
}

/*
  Minimizes f over the integral points of the face. Returns a point X with
  f(X) < f(A), or another point of the face where f is minimal, or none if
  A is the unique minimizer (checked with the minimum and maximum of the k
  coordinates t_i over the face where f = f(A)).
 */
template <typename T, typename Tint>
std::optional<MyVector<T>>
igusa_face_new_point(IgusaSpace<T, Tint> &space,
                     IgusaFaceData<T, Tint> const &face, MyVector<T> const &f,
                     std::ostream &os) {
  int dim = space.dim;
  int n_v = face.Equa.rows();
  MyMatrix<T> NoIneq(0, dim + 1);
  T f_A = ILP_EvaluateRow(f, face.x_A);
  std::optional<IgusaMinimum<T>> opt =
      igusa_integral_minimization(space, f, NoIneq, face.Equa, os);
  IgusaMinimum<T> res = unfold_opt(opt, "The face is not empty");
  if (res.value < f_A) {
    return res.x;
  }
  MyMatrix<T> Equa2(n_v + 1, dim + 1);
  for (int i = 0; i < n_v; i++) {
    for (int j = 0; j <= dim; j++) {
      Equa2(i, j) = face.Equa(i, j);
    }
  }
  for (int j = 0; j <= dim; j++) {
    Equa2(n_v, j) = f(j);
  }
  Equa2(n_v, 0) -= f_A;
  for (int i = 0; i < face.k; i++) {
    MyVector<T> g = ZeroVector<T>(dim + 1);
    for (int j = 0; j < dim; j++) {
      g(j + 1) = face.N(i, j);
    }
    T g_A = ILP_EvaluateRow(g, face.x_A);
    for (int sign = -1; sign <= 1; sign += 2) {
      MyVector<T> gs = T(sign) * g;
      std::optional<IgusaMinimum<T>> opt_g =
          igusa_integral_minimization(space, gs, NoIneq, Equa2, os);
      IgusaMinimum<T> res_g = unfold_opt(opt_g, "The face is not empty");
      if (res_g.value != T(sign) * g_A) {
        return res_g.x;
      }
    }
  }
  return {};
}

template <typename T, typename Tint>
IgusaVertexTestResult<T>
igusa_vertex_test_face(IgusaSpace<T, Tint> &space, MyMatrix<T> const &A,
                       std::ostream &os) {
  (void)igusa_insert_short_vector_cuts(space, A, os);
  IgusaFaceData<T, Tint> face = igusa_face_data(space, A, os);
  IgusaVertexTestResult<T> result;
  result.rank_min = face.rank_min;
  result.dim_face = face.k;
  result.n_iter = 0;
  if (face.k == 0) {
    result.is_vertex = true;
    return result;
  }
  IgusaFaceDirections<T> dirs;
  for (int i = 0; i < face.q; i++) {
    MyVector<T> w = ZeroVector<T>(face.q);
    w(i) = T(1);
    dirs.R_t.push_back(igusa_face_recession_direction(space, face, w));
  }
  while (true) {
    result.n_iter++;
    MyVector<T> c;
    if (dirs.S_t.empty()) {
      c = igusa_face_initial_functional(space, face, A);
    } else {
      std::optional<MyVector<T>> opt_c =
          igusa_face_separation(face, dirs, os);
      if (!opt_c) {
        igusa_face_convex_combination(face, dirs, A, result, os);
        result.is_vertex = false;
        return result;
      }
      c = *opt_c;
    }
    if (face.q > 0) {
      MyMatrix<T> Hq = igusa_face_recession_matrix(space, face, c);
      if (!IsPositiveDefinite(Hq, os)) {
        MyVector<Tint> w =
            igusa_non_positive_vector<T, Tint>(Hq, T(1) / T(1000000), os);
        dirs.R_t.push_back(igusa_face_recession_direction(
            space, face, UniversalVectorConversion<T, Tint>(w)));
#ifdef DEBUG_IGUSA_VERTEX_FACE
        os << "IGUSA_VERTEX_FACE: iter=" << result.n_iter
           << " new recession direction\n";
#endif
        continue;
      }
    }
    MyVector<T> f = igusa_face_coercive_function(space, face, c, os);
    std::optional<MyVector<T>> opt_x = igusa_face_new_point(space, face, f, os);
    if (!opt_x) {
      result.is_vertex = true;
      result.h = c;
      return result;
    }
    MyVector<T> x_D = *opt_x - face.x_A;
    dirs.S_t.push_back(igusa_face_coordinates(face, x_D));
    dirs.S_X.push_back(igusa_matrix(space, *opt_x));
#ifdef DEBUG_IGUSA_VERTEX_FACE
    os << "IGUSA_VERTEX_FACE: iter=" << result.n_iter
       << " new point, |S|=" << dirs.S_t.size() << "\n";
#endif
  }
}

inline FullNamelist NAMELIST_GetStandard_IGUSA_VERTEX_TEST() {
  std::map<std::string, SingleBlock> ListBlock;
  {
    std::map<std::string, std::string> ListStringValues;
    std::map<std::string, int> ListIntValues;
    std::map<std::string, bool> ListBoolValues;
    ListStringValues["arithmetic"] = "gmp";
    ListStringValues["IlpMethod"] = "default";
    ListStringValues["OutFile"] = "stderr";
    // A list of forms (ListMatrix format) to be tested
    ListStringValues["FileListForm"] = "unset";
    SingleBlock BlockDATA;
    BlockDATA.setListStringValues(ListStringValues);
    BlockDATA.setListIntValues(ListIntValues);
    BlockDATA.setListBoolValues(ListBoolValues);
    ListBlock["DATA"] = BlockDATA;
  }
  ListBlock["TSPACE"] = SINGLEBLOCK_Get_Tspace_Description();
  return FullNamelist(ListBlock);
}

// clang-format off
#endif  // SRC_IGUSA_IGUSA_VERTEX_FACE_H_
// clang-format on
