// Copyright (C) 2026 Mathieu Dutour Sikiric <mathieu.dutour@gmail.com>
#ifndef SRC_ERDAHL_ERDAHL_CUTS_H_
#define SRC_ERDAHL_ERDAHL_CUTS_H_

// clang-format off
#include "erdahl_polytope_enumeration.h"
#include <map>
#include <set>
#include <utility>
#include <vector>
// clang-format on

#ifdef DEBUG
#define DEBUG_ERDAHL_CUTS
#endif

#ifdef SANITY_CHECK
#define SANITY_CHECK_ERDAHL_CUTS
#endif

/*
  The cone of the Erdahl cuts.

  A degree 2 function on Z^n is f(x) = X F X^T with X = (1, x) and F a
  symmetric matrix of size n+1. For v = (b, a) in Z^{n+1} the cut
      phi(phi - 1) with phi(x) = v.X = b + a.x
  has the matrix C_v = v^T v - (v^T e_0 + e_0^T v) / 2. The cone CUT_E(n)
  is the closure of the cone generated by the cuts. It is contained in the
  Erdahl cone and, the perfect functions being extreme, it is equal to it
  if and only if all the perfect Delaunay polyhedra are strips
  {0 <= phi <= 1}, i.e. for n <= 5.

  Duality. For M symmetric of size n+1,
      <M, C_v> = M[v] - (M e_0).v = M[v - e_0/2] - M[e_0/2].
  So M is a valid inequality of CUT_E(n) if and only if the function
      h_M(v) = M[v - e_0/2] - M[e_0/2]
  on Z^{n+1} is nonnegative: the dual of CUT_E(n) is the face of the
  Erdahl cone of Z^{n+1} relative to the functions of center e_0/2 made of
  the functions vanishing at 0 (and so at e_0). Its extreme rays are the
  centrally symmetric perfect Delaunay polyhedra D of center e_0/2 that
  contain 0, i.e. a centrally symmetric perfect polyhedron with one of
  its antipodal pairs {u, u*} moved to {0, e_0}. The facets of CUT_E(n)
  up to Aff(Z^n) are then the orbits of the pairs (D, {u, u*}) under the
  stabilizer of the center.

  Checking an inequality M, i.e. finding the cut minimizing <M, C_v>, is a
  closest vector problem: the minimum of h_M over Z^{n+1}.
 */

// The matrix C_v of the cut phi(phi - 1) for phi = v.(1, x).
template <typename T, typename Tint>
MyMatrix<T> erdahl_cut_matrix(MyVector<Tint> const &v) {
  int np1 = v.size();
  MyVector<T> v_T = UniversalVectorConversion<T, Tint>(v);
  MyMatrix<T> C = v_T * v_T.transpose();
  for (int i = 0; i < np1; i++) {
    C(0, i) -= v_T(i) / 2;
    C(i, 0) -= v_T(i) / 2;
  }
  return C;
}

// The function h_M on Z^{n+1}, as a matrix of size n+2.
template <typename T> MyMatrix<T> erdahl_cut_dual_function(MyMatrix<T> const &M) {
  int np1 = M.rows();
  MyMatrix<T> G = ZeroMatrix<T>(np1 + 1, np1 + 1);
  for (int i = 0; i < np1; i++) {
    for (int j = 0; j < np1; j++) {
      G(1 + i, 1 + j) = M(i, j);
    }
    G(0, 1 + i) = -M(i, 0) / 2;
    G(1 + i, 0) = -M(i, 0) / 2;
  }
  return G;
}

// The coefficients of M -> <M, X> = trace(M X) on the basis E_ii,
// E_ij + E_ji (i < j) of the symmetric matrices.
template <typename T> MyVector<T> erdahl_cut_pairing_row(MyMatrix<T> const &X) {
  int np1 = X.rows();
  MyVector<T> V((np1 * (np1 + 1)) / 2);
  int pos = 0;
  for (int i = 0; i < np1; i++) {
    for (int j = i; j < np1; j++) {
      V(pos) = (i == j) ? X(i, i) : T(2) * X(i, j);
      pos++;
    }
  }
  return V;
}

template <typename T>
MyMatrix<T> erdahl_cut_symmetric_from_coordinates(MyVector<T> const &c, int np1) {
  MyMatrix<T> M(np1, np1);
  int pos = 0;
  for (int i = 0; i < np1; i++) {
    for (int j = i; j < np1; j++) {
      M(i, j) = c(pos);
      M(j, i) = c(pos);
      pos++;
    }
  }
  return M;
}

template <typename T> T erdahl_cut_pairing(MyMatrix<T> const &M, MyMatrix<T> const &X) {
  return (M.cwiseProduct(X)).sum();
}

// The rank of the cuts of the points of the zero set of h_M (the tight
// cuts of the inequality M), translated by the isotropy lattice.
template <typename T, typename Tint>
int erdahl_cut_tight_rank(ErdahlLatticeSet<Tint> const &ls) {
  std::vector<MyVector<T>> l_row;
  int np1 = ls.EXT.cols() - 1;
  auto insert = [&](MyVector<Tint> const &e) -> void {
    MyVector<Tint> v(np1);
    for (int i = 0; i < np1; i++) {
      v(i) = e(1 + i);
    }
    l_row.push_back(erdahl_cut_pairing_row(erdahl_cut_matrix<T, Tint>(v)));
  };
  for (int i = 0; i < ls.EXT.rows(); i++) {
    MyVector<Tint> e = GetMatrixRow(ls.EXT, i);
    insert(e);
    for (int k = 0; k < ls.L.rows(); k++) {
      for (int sign = -1; sign <= 1; sign += 2) {
        MyVector<Tint> f = e;
        for (int j = 0; j < np1; j++) {
          f(1 + j) += sign * ls.L(k, j);
        }
        insert(f);
      }
    }
  }
  MyMatrix<T> Mrow = MatrixFromVectorFamilyDim((np1 * (np1 + 1)) / 2, l_row);
  return RankMat(Mrow);
}

template <typename T, typename Tint> struct ErdahlCutFacet {
  // The inequality <M, F> >= 0, M of size n+1.
  MyMatrix<T> M;
  // The perfect polyhedron D of Z^{n+1} of center e_0/2, containing 0 and
  // e_0, whose function is h_M.
  DelaunayPolyhedron<T, Tint> D;
  // The number of antipodal pairs of D in the orbit.
  size_t orbit_size;
  // The number of tight cuts (pairs {v, e_0 - v} of vertices of D) and
  // the rank of their span, (n+1)(n+2)/2 - 1 for a facet.
  size_t n_tight;
  int rank_tight;
};

/*
  The facets of CUT_E(n) coming from the centrally symmetric perfect
  polytope D of Z^{n+1} relative to the space W of the functions of
  center c: one for each orbit of antipodal pairs of vertices under
  Aut_W(D). The difference of two antipodal vertices of a polytope is
  primitive: the lattice points strictly between them would be inside the
  Delaunay ellipsoid.
 */
template <typename T, typename Tint, typename Tgroup>
std::vector<ErdahlCutFacet<T, Tint>>
erdahl_cut_facets_of_polytope(ErdahlFunctionSpace<T> const &W,
                              DelaunayPolyhedron<T, Tint> const &D,
                              std::ostream &os) {
  using Telt = typename Tgroup::Telt;
  using Tidx = typename Telt::Tidx;
  int np1 = W.n;
  int n_ext = D.EXT.rows();
  MyVector<T> const &c = *W.center;
  // The antipode of each vertex.
  std::map<MyVector<Tint>, int> map_vert;
  for (int i = 0; i < n_ext; i++) {
    map_vert[GetMatrixRow(D.EXT, i)] = i;
  }
  std::vector<int> antipode(n_ext);
  for (int i = 0; i < n_ext; i++) {
    MyVector<Tint> e = GetMatrixRow(D.EXT, i);
    MyVector<Tint> f(np1 + 1);
    f(0) = 1;
    for (int j = 0; j < np1; j++) {
      f(1 + j) = UniversalScalarConversion<Tint, T>(2 * c(j)) - e(1 + j);
    }
    auto iter = map_vert.find(f);
    if (iter == map_vert.end()) {
      std::cerr << "ERDAHL: the polytope is not centrally symmetric\n";
      throw TerminalException{1};
    }
    antipode[i] = iter->second;
  }
  ErdahlPolytopeGroup<T, Tint, Tgroup> grp =
      erdahl_polytope_group<T, Tint, Tgroup>(W, D, os);
  // The orbits of the pairs, a pair being given by its smaller vertex.
  std::vector<int> orbit_of(n_ext, -1);
  std::vector<std::pair<int, size_t>> l_orbit;
  for (int i = 0; i < n_ext; i++) {
    int i_min = std::min(i, antipode[i]);
    if (orbit_of[i_min] != -1) {
      continue;
    }
    int i_orbit = l_orbit.size();
    std::vector<int> l_work{i_min};
    orbit_of[i_min] = i_orbit;
    size_t pos = 0;
    while (pos < l_work.size()) {
      int j = l_work[pos];
      pos++;
      for (auto &eGen : grp.grp.GeneratorsOfGroup()) {
        int k = OnPoints(static_cast<Tidx>(j), eGen);
        int k_min = std::min(k, antipode[k]);
        if (orbit_of[k_min] == -1) {
          orbit_of[k_min] = i_orbit;
          l_work.push_back(k_min);
        }
      }
    }
    l_orbit.push_back({i_min, l_work.size()});
  }
  std::vector<ErdahlCutFacet<T, Tint>> l_facet;
  for (auto &orbit : l_orbit) {
    MyVector<Tint> u = GetMatrixRow(D.EXT, orbit.first);
    MyVector<Tint> u_star = GetMatrixRow(D.EXT, antipode[orbit.first]);
    MyVector<Tint> d(np1);
    MyVector<Tint> u_x(np1);
    for (int j = 0; j < np1; j++) {
      d(j) = u_star(1 + j) - u(1 + j);
      u_x(j) = u(1 + j);
    }
    // x -> x A + t with u -> 0 and u* -> e_0, i.e. d A = e_0.
    MyMatrix<Tint> A = Inverse(erdahl_unimodular_with_first_row(d));
    MyVector<Tint> t = -(A.transpose() * u_x);
    MyMatrix<Tint> g = IdentityMat<Tint>(np1 + 1);
    for (int i = 0; i < np1; i++) {
      for (int j = 0; j < np1; j++) {
        g(1 + i, 1 + j) = A(i, j);
      }
      g(0, 1 + i) = t(i);
    }
    DelaunayPolyhedron<T, Tint> Dg = erdahl_apply_transformation(D, g);
    MyMatrix<T> M(np1, np1);
    for (int i = 0; i < np1; i++) {
      for (int j = 0; j < np1; j++) {
        M(i, j) = Dg.F(1 + i, 1 + j);
      }
    }
    // The function of Dg is h_M up to a positive multiple.
    MyMatrix<T> H = erdahl_cut_dual_function(M);
    if (RemoveFractionMatrix(H) != RemoveFractionMatrix(Dg.F)) {
      std::cerr << "ERDAHL: the moved function should be h_M\n";
      throw TerminalException{1};
    }
    M = RemoveFractionMatrix(M);
    ErdahlLatticeSet<Tint> ls = erdahl_lattice_set(Dg);
    size_t n_tight = ls.EXT.rows() / 2;
    int rank_tight = erdahl_cut_tight_rank<T, Tint>(ls);
    l_facet.push_back({M, Dg, orbit.second, n_tight, rank_tight});
  }
  return l_facet;
}

template <typename T, typename Tint> struct ErdahlCutSeparation {
  // The minimum of <M, F> over the valid inequalities M normalized by
  // <M, F0> = 1: F is in CUT_E(n) if and only if it is >= 0.
  T value;
  // An optimal inequality, extreme in the dual cone.
  MyMatrix<T> M;
  // The zero set of h_M, i.e. the tight cuts.
  ErdahlLatticeSet<Tint> tight;
  size_t n_iter;
  size_t n_constraint;
};

/*
  The most violated inequality of CUT_E(n) for the function F, by a
  cutting plane method: the linear program in M with the constraints
  <M, C_v> >= 0 for the v found so far, and <M, F0> = 1 for F0 the sum of
  the cuts of an initial spanning set V0 (which makes the feasible set
  bounded), minimizing <M, F>. The optimal M is checked with the closest
  vector problem of h_M: a lattice point where h_M is negative gives a new
  cut, a direction u with M[u] < 0 the constraint M[u] >= 0. At the end M
  is a vertex of the feasible set lying in the dual cone, so an extreme ray
  of it.
 */
template <typename T, typename Tint>
ErdahlCutSeparation<T, Tint> erdahl_cut_separation(MyMatrix<T> const &F,
                                                   std::ostream &os) {
  int np1 = F.rows();
  int dim = (np1 * (np1 + 1)) / 2;
  std::vector<MyVector<T>> l_ineq;
  std::set<MyVector<Tint>> set_v;
  // v and e_0 - v give the same cut: the smaller one is kept.
  auto insert_cut = [&](MyVector<Tint> const &v_in) -> void {
    MyVector<Tint> v_alt = -v_in;
    v_alt(0) += 1;
    MyVector<Tint> v = std::min(v_in, v_alt);
    if (IsZeroVector(v) || (v(0) == 1 && IsZeroVector(MyVector<Tint>(v.tail(np1 - 1))))) {
      return;
    }
    if (set_v.insert(v).second) {
      MyVector<T> row(dim + 1);
      row(0) = 0;
      MyVector<T> pr = erdahl_cut_pairing_row(erdahl_cut_matrix<T, Tint>(v));
      for (int i = 0; i < dim; i++) {
        row(1 + i) = pr(i);
      }
      l_ineq.push_back(row);
    }
  };
  auto insert_direction = [&](MyVector<Tint> const &u) -> void {
    MyVector<T> u_T = UniversalVectorConversion<T, Tint>(u);
    MyVector<T> pr = erdahl_cut_pairing_row(MyMatrix<T>(u_T * u_T.transpose()));
    MyVector<T> row(dim + 1);
    row(0) = 0;
    for (int i = 0; i < dim; i++) {
      row(1 + i) = pr(i);
    }
    l_ineq.push_back(row);
  };
  // V0: the vectors with entries in {-1, 0, 1, 2} and at most three
  // nonzero entries; their cuts span the symmetric matrices.
  std::vector<MyVector<Tint>> V0;
  std::vector<int> l_val{-1, 1, 2};
  for (int i = 0; i < np1; i++) {
    for (auto &a : l_val) {
      MyVector<Tint> v = ZeroVector<Tint>(np1);
      v(i) = a;
      V0.push_back(v);
      for (int j = i + 1; j < np1; j++) {
        for (auto &b : l_val) {
          MyVector<Tint> w = v;
          w(j) = b;
          V0.push_back(w);
          for (int k = j + 1; k < np1; k++) {
            for (auto &cc : l_val) {
              MyVector<Tint> x = w;
              x(k) = cc;
              V0.push_back(x);
            }
          }
        }
      }
    }
  }
  MyMatrix<T> F0 = ZeroMatrix<T>(np1, np1);
  for (auto &v : V0) {
    insert_cut(v);
    F0 += erdahl_cut_matrix<T, Tint>(v);
  }
  {
    std::vector<MyVector<T>> l_row;
    for (auto &v : V0) {
      l_row.push_back(erdahl_cut_pairing_row(erdahl_cut_matrix<T, Tint>(v)));
    }
    if (RankMat(MatrixFromVectorFamilyDim(dim, l_row)) != dim) {
      std::cerr << "ERDAHL: the initial cuts should span\n";
      throw TerminalException{1};
    }
  }
  MyVector<T> pr0 = erdahl_cut_pairing_row(F0);
  MyVector<T> prF = erdahl_cut_pairing_row(F);
  size_t n_iter = 0;
  while (true) {
    n_iter++;
    int n_ineq = l_ineq.size();
    MyMatrix<T> ListIneq(n_ineq + 2, dim + 1);
    for (int i = 0; i < n_ineq; i++) {
      AssignMatrixRow(ListIneq, i, l_ineq[i]);
    }
    // <M, F0> = 1 as two inequalities.
    ListIneq(n_ineq, 0) = -1;
    ListIneq(n_ineq + 1, 0) = 1;
    for (int i = 0; i < dim; i++) {
      ListIneq(n_ineq, 1 + i) = pr0(i);
      ListIneq(n_ineq + 1, 1 + i) = -pr0(i);
    }
    MyVector<T> ToBeMinimized(dim + 1);
    ToBeMinimized(0) = 0;
    for (int i = 0; i < dim; i++) {
      ToBeMinimized(1 + i) = prF(i);
    }
    LpSolution<T> eSol = SIMPLEX_LinearProgramming(ListIneq, ToBeMinimized, os);
    if (!eSol.DirectSolution) {
      std::cerr << "ERDAHL: the separation linear program should have an "
                   "optimal solution\n";
      throw TerminalException{1};
    }
    MyMatrix<T> M = erdahl_cut_symmetric_from_coordinates(*eSol.DirectSolution, np1);
    auto res = erdahl_zero_set<T, Tint>(erdahl_cut_dual_function(M), os);
#ifdef DEBUG_ERDAHL_CUTS
    os << "ERDAHL: cut separation, iter=" << n_iter << " |ineq|=" << n_ineq
       << " value=" << erdahl_cut_pairing(M, F)
       << " valid=" << res.is_ok() << "\n";
#endif
    if (res.is_ok()) {
      return {erdahl_cut_pairing(M, F), M, res.get_ok(), n_iter, l_ineq.size()};
    }
    ErdahlNegativeWitness<Tint> const &wit = res.get_err();
    // The points where h_M is negative and their neighbors, which are
    // typically negative as well: one cut per iteration converges slowly.
    for (auto &e : wit.points) {
      MyVector<Tint> v(np1);
      for (int i = 0; i < np1; i++) {
        v(i) = e(1 + i);
      }
      insert_cut(v);
      for (int i = 0; i < np1; i++) {
        for (int sign = -1; sign <= 1; sign += 2) {
          MyVector<Tint> w = v;
          w(i) += sign;
          if (erdahl_cut_pairing(M, erdahl_cut_matrix<T, Tint>(w)) < 0) {
            insert_cut(w);
          }
        }
      }
    }
    for (auto &e : wit.directions) {
      MyVector<Tint> u(np1);
      for (int i = 0; i < np1; i++) {
        u(i) = e(1 + i);
      }
      insert_direction(u);
    }
    if (wit.points.empty() && wit.directions.empty()) {
      std::cerr << "ERDAHL: the closest vector problem gave no witness\n";
      throw TerminalException{1};
    }
  }
}

// clang-format off
#endif  // SRC_ERDAHL_ERDAHL_CUTS_H_
// clang-format on
