// Copyright (C) 2026 Mathieu Dutour Sikiric <mathieu.dutour@gmail.com>
#ifndef SRC_ERDAHL_ERDAHL_POLYTOPE_H_
#define SRC_ERDAHL_ERDAHL_POLYTOPE_H_

// clang-format off
#include "erdahl_polyhedron.h"
#include "PolytopeEquiStabInt.h"
#include "POLY_RecursiveDualDesc.h"
#include <map>
#include <optional>
#include <vector>
// clang-format on

#ifdef DEBUG
#define DEBUG_ERDAHL_POLYTOPE
#endif

#ifdef SANITY_CHECK
#define SANITY_CHECK_ERDAHL_POLYTOPE
#endif

#ifdef TIMINGS
#define TIMINGS_ERDAHL_POLYTOPE
#endif

/*
  Delaunay polyhedra with a trivial isotropy lattice, i.e. Delaunay
  polytopes, relative to a space W of functions.

  * Aut_W(D): the affine integral transformations g preserving D and W.
    Such g preserve the scalar products (1,x) M (1,y)^T with M the inverse
    of sum_{x in D} (1,x)^T (1,x) (the "discriminant" Gram matrix of the
    GAP code, InfDel_GetGramDiscMat), so they are found as the integral
    automorphisms of that configuration, and then filtered for W.
  * The sub-polyhedra D' subset D with rank_W(D') = rank_W(D) + 1. By
    Theorem "BasicResultErdahlCone" (iii) of the paper, they are the
    facets of the cone generated by the evaluation vectors of the points
    of D, here restricted to W: v_x = (f_i(x))_i for (f_i) the basis of W.
    For each facet the function of W vanishing on it and positive on the
    rest of D is g, which shows that the facet is a Delaunay polyhedron
    (g + k f_D is in Erdahl(n) for k large); its function is then the
    canonical one of erdahl_canonical_function.
 */

template <typename T, typename Tint, typename Tgroup> struct ErdahlPolytopeGroup {
  // Affine integral transformations (n+1) x (n+1) preserving D and W.
  std::vector<MyMatrix<Tint>> l_gen;
  // The same group, acting on the rows of D.EXT.
  Tgroup grp;
};

template <typename T, typename Tint>
MyMatrix<T> erdahl_discriminant_matrix(MyMatrix<Tint> const &EXT) {
  int dim = EXT.cols();
  MyMatrix<T> Q = ZeroMatrix<T>(dim, dim);
  for (int i = 0; i < EXT.rows(); i++) {
    MyVector<T> e = UniversalVectorConversion<T, Tint>(GetMatrixRow(EXT, i));
    Q += e * e.transpose();
  }
  return Inverse(Q);
}

// The bijection i -> j from the rows of EXT1 to the rows of EXT2 with
// EXT1.row(i) g = EXT2.row(j), if e -> e g maps one set onto the other.
template <typename Tint, typename Telt>
std::optional<Telt> erdahl_permutation_of_rows(MyMatrix<Tint> const &EXT1,
                                               MyMatrix<Tint> const &EXT2,
                                               MyMatrix<Tint> const &g) {
  using Tidx = typename Telt::Tidx;
  std::map<MyVector<Tint>, Tidx> map_row;
  int n_row = EXT2.rows();
  if (EXT1.rows() != n_row) {
    return {};
  }
  for (int i = 0; i < n_row; i++) {
    map_row[GetMatrixRow(EXT2, i)] = i;
  }
  std::vector<Tidx> v(n_row);
  for (int i = 0; i < n_row; i++) {
    MyVector<Tint> e = g.transpose() * GetMatrixRow(EXT1, i);
    auto iter = map_row.find(e);
    if (iter == map_row.end()) {
      return {};
    }
    v[i] = iter->second;
  }
  return Telt(v);
}

template <typename T, typename Tint, typename Tgroup>
ErdahlPolytopeGroup<T, Tint, Tgroup>
erdahl_polytope_group(ErdahlFunctionSpace<T> const &W,
                      DelaunayPolyhedron<T, Tint> const &D, std::ostream &os) {
  using Telt = typename Tgroup::Telt;
  using Tidx = typename Telt::Tidx;
  if (D.L.rows() > 0) {
    std::cerr << "ERDAHL: erdahl_polytope_group requires a polytope\n";
    throw TerminalException{1};
  }
  int n_ext = D.EXT.rows();
  std::vector<MyMatrix<T>> ListMat{erdahl_discriminant_matrix<T, Tint>(D.EXT)};
  std::vector<T> Vdiag(n_ext, T(0));
  std::vector<MyMatrix<Tint>> l_gen_all =
      GetIntAutomorphism_ListMat_Vdiag<T, Tint, Tgroup>(D.EXT, ListMat, Vdiag,
                                                        os);
  auto get_perm = [&](MyMatrix<Tint> const &g) -> Telt {
    std::optional<Telt> opt =
        erdahl_permutation_of_rows<Tint, Telt>(D.EXT, D.EXT, g);
    if (!opt) {
      std::cerr << "ERDAHL: an automorphism does not preserve the vertex set\n";
      throw TerminalException{1};
    }
    return *opt;
  };
  bool all_preserve = true;
  std::vector<Telt> l_perm;
  for (auto &g : l_gen_all) {
    l_perm.push_back(get_perm(g));
    if (!erdahl_preserves_space(W, g)) {
      all_preserve = false;
    }
  }
  Telt id(static_cast<Tidx>(n_ext));
  if (all_preserve) {
    Tgroup grp(l_perm, id);
    return {l_gen_all, grp};
  }
  /*
    Some automorphisms of D do not preserve W. The subgroup of those that do
    is obtained by testing all the elements, which is fine for the orders
    encountered here (the groups of Delaunay polytopes).
   */
  Tgroup grp_all(l_perm, id);
#ifdef DEBUG_ERDAHL_POLYTOPE
  os << "ERDAHL: filtering the group of order " << grp_all.size()
     << " for the preservation of W\n";
#endif
  MyMatrix<T> EXT_T = UniversalMatrixConversion<T, Tint>(D.EXT);
  std::vector<MyMatrix<Tint>> l_gen;
  std::vector<Telt> l_perm_sel;
  for (auto &elt : grp_all) {
    MyMatrix<T> g_T = FindTransformation(EXT_T, EXT_T, elt);
    MyMatrix<Tint> g = UniversalMatrixConversion<Tint, T>(g_T);
    if (erdahl_preserves_space(W, g)) {
      l_gen.push_back(g);
      l_perm_sel.push_back(elt);
    }
  }
  Tgroup grp(l_perm_sel, id);
  return {l_gen, grp};
}

/*
  An affine integral transformation g preserving W with D1.EXT g = D2.EXT
  (as sets), if one exists.
 */
template <typename T, typename Tint, typename Tgroup>
std::optional<MyMatrix<Tint>>
erdahl_polytope_equivalence(ErdahlFunctionSpace<T> const &W,
                            DelaunayPolyhedron<T, Tint> const &D1,
                            DelaunayPolyhedron<T, Tint> const &D2,
                            std::ostream &os) {
  using Telt = typename Tgroup::Telt;
  if (D1.L.rows() > 0 || D2.L.rows() > 0) {
    std::cerr << "ERDAHL: erdahl_polytope_equivalence requires polytopes\n";
    throw TerminalException{1};
  }
  if (D1.EXT.rows() != D2.EXT.rows()) {
    return {};
  }
  int n_ext = D1.EXT.rows();
  std::vector<MyMatrix<T>> ListMat1{erdahl_discriminant_matrix<T, Tint>(D1.EXT)};
  std::vector<MyMatrix<T>> ListMat2{erdahl_discriminant_matrix<T, Tint>(D2.EXT)};
  std::vector<T> Vdiag(n_ext, T(0));
  std::optional<MyMatrix<Tint>> opt =
      TestIntEquivalence_ListMat_Vdiag<T, Tint, Tgroup>(
          D1.EXT, ListMat1, Vdiag, D2.EXT, ListMat2, Vdiag, os);
  if (!opt) {
    return {};
  }
  // The returned P has P M1 P^T = M2, that is D2.EXT P is D1.EXT permuted.
  // The transformation mapping D1 to D2 is its inverse.
  MyMatrix<Tint> g = Inverse(*opt);
  if (!erdahl_permutation_of_rows<Tint, Telt>(D1.EXT, D2.EXT, g)) {
    std::cerr << "ERDAHL: the equivalence does not map D1 to D2\n";
    throw TerminalException{1};
  }
  if (erdahl_preserves_space(W, g)) {
    return g;
  }
  // The equivalences are the g h for h in Aut(D2): search one preserving W.
  ErdahlFunctionSpace<T> Wfull = erdahl_full_space<T>(W.n);
  ErdahlPolytopeGroup<T, Tint, Tgroup> grp2 =
      erdahl_polytope_group<T, Tint, Tgroup>(Wfull, D2, os);
  MyMatrix<T> EXT2_T = UniversalMatrixConversion<T, Tint>(D2.EXT);
  for (auto &elt : grp2.grp) {
    MyMatrix<T> h_T = FindTransformation(EXT2_T, EXT2_T, elt);
    MyMatrix<Tint> h = UniversalMatrixConversion<Tint, T>(h_T);
    MyMatrix<Tint> gh = g * h;
    if (erdahl_preserves_space(W, gh)) {
      return gh;
    }
  }
  return {};
}

/*
  The evaluation vectors of the points of D, grouped into classes of
  positively proportional vectors (for W the centered space the two points
  of a pair {x, 2c - x} have the same vector).
 */
template <typename T> struct ErdahlEvaluationClasses {
  // One row per class.
  MyMatrix<T> EXTcone;
  // The class of each vertex.
  std::vector<size_t> vert_to_class;
  // The vertices of each class.
  std::vector<std::vector<size_t>> class_to_verts;
};

template <typename T>
MyVector<T> erdahl_positive_normalization(MyVector<T> const &V) {
  for (int i = 0; i < V.size(); i++) {
    if (V(i) != 0) {
      T scal = T_abs(V(i));
      return V / scal;
    }
  }
  return V;
}

template <typename T, typename Tint>
ErdahlEvaluationClasses<T>
erdahl_evaluation_classes(ErdahlFunctionSpace<T> const &W,
                          MyMatrix<Tint> const &EXT) {
  std::map<MyVector<T>, size_t> map_class;
  std::vector<MyVector<T>> l_vect;
  std::vector<size_t> vert_to_class;
  std::vector<std::vector<size_t>> class_to_verts;
  for (int i = 0; i < EXT.rows(); i++) {
    MyVector<Tint> e = GetMatrixRow(EXT, i);
    MyVector<T> V =
        erdahl_positive_normalization(erdahl_evaluation_vector(W, e));
    auto iter = map_class.find(V);
    if (iter == map_class.end()) {
      size_t pos = l_vect.size();
      map_class[V] = pos;
      l_vect.push_back(V);
      class_to_verts.push_back({static_cast<size_t>(i)});
      vert_to_class.push_back(pos);
    } else {
      class_to_verts[iter->second].push_back(i);
      vert_to_class.push_back(iter->second);
    }
  }
  MyMatrix<T> EXTcone = MatrixFromVectorFamilyDim(W.basis.size(), l_vect);
  return {EXTcone, vert_to_class, class_to_verts};
}

template <typename Tint> struct ErdahlSubPolyhedraPolytope {
  // Orbit representatives of the full dimensional sub-polyhedra of rank
  // r+1, as indices of the rows of D.EXT.
  std::vector<Face> l_face;
  // Orbit representatives of the faces of the cone whose zero sets are not
  // full dimensional (possible for a subspace W, not for the full space).
  std::vector<Face> l_face_lowdim;
};

/*
  The function of W vanishing on the vertices of eFace and positive on the
  other vertices of D.
 */
template <typename T, typename Tint>
MyMatrix<T> erdahl_function_of_face(ErdahlFunctionSpace<T> const &W,
                                    DelaunayPolyhedron<T, Tint> const &D,
                                    Face const &eFace) {
  int n_ext = D.EXT.rows();
  int np1 = D.EXT.cols();
  std::vector<MyVector<Tint>> l_in;
  for (int i = 0; i < n_ext; i++) {
    if (eFace[i] == 1) {
      l_in.push_back(GetMatrixRow(D.EXT, i));
    }
  }
  MyMatrix<Tint> EXTface = MatrixFromVectorFamilyDim(np1, l_in);
  ErdahlLatticeSet<Tint> ls{EXTface, MyMatrix<Tint>(0, np1 - 1)};
  std::vector<MyMatrix<T>> l_func = erdahl_vanishing_space(W, ls);
  for (auto &g : l_func) {
    int n_pos = 0;
    int n_neg = 0;
    for (int i = 0; i < n_ext; i++) {
      if (eFace[i] == 0) {
        MyVector<Tint> e = GetMatrixRow(D.EXT, i);
        T val = EvaluationQuadForm<T, Tint>(g, e);
        if (val > 0) {
          n_pos++;
        }
        if (val < 0) {
          n_neg++;
        }
      }
    }
    if (n_pos > 0 && n_neg > 0) {
      std::cerr << "ERDAHL: the function of the facet takes both signs\n";
      throw TerminalException{1};
    }
    if (n_pos + n_neg == 0) {
      // A function of Space_W(D).
      continue;
    }
    int n_out = n_ext - EXTface.rows();
    if (n_pos + n_neg != n_out) {
      std::cerr << "ERDAHL: the function of the facet vanishes outside of it\n";
      throw TerminalException{1};
    }
    MyMatrix<T> gpos = g;
    if (n_neg > 0) {
      gpos = -g;
    }
    return gpos;
  }
  std::cerr << "ERDAHL: failed to find the function of the facet\n";
  throw TerminalException{1};
}

template <typename T, typename Tint, typename Tgroup>
ErdahlSubPolyhedraPolytope<Tint>
erdahl_sub_polyhedra_polytope(ErdahlFunctionSpace<T> const &W,
                              DelaunayPolyhedron<T, Tint> const &D,
                              std::string const &FileDualDesc,
                              std::ostream &os) {
  using Telt = typename Tgroup::Telt;
  using Tidx = typename Telt::Tidx;
  int n_ext = D.EXT.rows();
#ifdef TIMINGS_ERDAHL_POLYTOPE
  MicrosecondTime time;
#endif
  ErdahlPolytopeGroup<T, Tint, Tgroup> grp =
      erdahl_polytope_group<T, Tint, Tgroup>(W, D, os);
#ifdef TIMINGS_ERDAHL_POLYTOPE
  os << "|ERDAHL: polytope, Aut_W(D) |EXT|=" << n_ext << "|=" << time << "\n";
#endif
  ErdahlEvaluationClasses<T> ec = erdahl_evaluation_classes(W, D.EXT);
  int n_class = ec.class_to_verts.size();
  // The action on the classes.
  std::vector<Telt> l_perm_class;
  for (auto &eGen : grp.grp.GeneratorsOfGroup()) {
    std::vector<Tidx> v(n_class);
    for (int i_class = 0; i_class < n_class; i_class++) {
      size_t i_vert = ec.class_to_verts[i_class][0];
      size_t j_vert = OnPoints(static_cast<Tidx>(i_vert), eGen);
      v[i_class] = ec.vert_to_class[j_vert];
    }
    l_perm_class.push_back(Telt(v));
  }
  Tgroup grp_class(l_perm_class, Telt(static_cast<Tidx>(n_class)));
#ifdef DEBUG_ERDAHL_POLYTOPE
  os << "ERDAHL: |EXT|=" << n_ext << " n_class=" << n_class
     << " |Aut_W(D)|=" << grp.grp.size() << " rank(cone)="
     << RankMat(ec.EXTcone) << "\n";
#endif
  /*
    The cone of evaluations usually has more symmetries than Aut_W(D): for
    the cube {0,1}^n it is the cone over the cut polytope CUT_{n+1}, whose
    group is larger than the one of the cube. The dual description is done
    with the full linear automorphism group of the cone, and the orbits are
    then split into orbits of Aut_W(D), as in POLY_RecursiveDualDesc.h.
   */
  using TintGroup = typename Tgroup::Tint;
  Tgroup grp_big = LinPolytope_Automorphism<T, Tgroup>(ec.EXTcone, os);
#ifdef TIMINGS_ERDAHL_POLYTOPE
  os << "|ERDAHL: polytope, Aut(cone)|=" << time << "\n";
#endif
  if (!grp_big.IsSubgroup(grp_class)) {
    std::cerr << "ERDAHL: Aut_W(D) should be a subgroup of the linear "
                 "automorphism group of the cone of evaluations\n";
    throw TerminalException{1};
  }
#ifdef DEBUG_ERDAHL_POLYTOPE
  os << "ERDAHL: |Aut(cone)|=" << grp_big.size()
     << " |Aut_W(D) on classes|=" << grp_class.size() << "\n";
#endif
  // The heuristics of the dual description (FileDualDesc = "unset" for the
  // default ones). The default ones do not split below level 1 of the
  // adjacency decomposition, which is not enough for large cones such as
  // CUT_8 (the 7-cube).
  int dim_cone = RankMat(ec.EXTcone);
  PolyHeuristicSerial<TintGroup> AllArr =
      Read_AllStandardHeuristicSerial_File<T, TintGroup>(FileDualDesc,
                                                         dim_cone, os);
  vectface vf_big =
      DualDescriptionStandard<T, Tgroup>(ec.EXTcone, grp_big, AllArr, os);
#ifdef TIMINGS_ERDAHL_POLYTOPE
  os << "|ERDAHL: polytope, dual description n_class=" << n_class
     << " |Aut(cone)|=" << grp_big.size() << " n_orbit=" << vf_big.size()
     << "|=" << time << "\n";
#endif
  vectface vf(n_class);
  if (grp_big.size() == grp_class.size()) {
    vf = std::move(vf_big);
  } else {
    // The orbit sizes are computed from the group when needed: the table
    // container enumerates all the divisors of the group order, which is
    // expensive for the large groups of these cones.
    FaceOrbitsizeGrpContainer<Tgroup> fotc(grp_big, std::move(vf_big));
    // As in OrbitSplittingListOrbitGen, the splitting method is chosen by
    // the heuristic.
    TintGroup index = grp_big.size() / grp_class.size();
    OrbitSplitInputInfo<TintGroup> info{grp_big.size(), grp_class.size(),
                                        index, fotc.size()};
    std::string method_split =
        typed_heuristic_evaluation(AllArr.OrbitSplitTechnique, info);
    vf = OrbitSplittingListOrbit_spec(grp_big, grp_class, fotc, method_split,
                                      os);
  }
#ifdef TIMINGS_ERDAHL_POLYTOPE
  os << "|ERDAHL: polytope, orbit splitting |Aut_W(D)|=" << grp_class.size()
     << " n_orbit=" << vf.size() << "|=" << time << "\n";
#endif
  ErdahlSubPolyhedraPolytope<Tint> ret;
  for (auto &eFaceClass : vf) {
    Face eFace(n_ext);
    for (int i = 0; i < n_ext; i++) {
      if (eFaceClass[ec.vert_to_class[i]] == 1) {
        eFace[i] = 1;
      }
    }
    std::vector<MyVector<Tint>> l_in;
    for (int i = 0; i < n_ext; i++) {
      if (eFace[i] == 1) {
        l_in.push_back(GetMatrixRow(D.EXT, i));
      }
    }
    MyMatrix<Tint> EXTface = MatrixFromVectorFamilyDim(D.EXT.cols(), l_in);
    ErdahlLatticeSet<Tint> ls{EXTface, MyMatrix<Tint>(0, D.EXT.cols() - 1)};
    if (erdahl_is_full_dimensional(ls)) {
      ret.l_face.push_back(eFace);
    } else {
      ret.l_face_lowdim.push_back(eFace);
    }
  }
  return ret;
}

template <typename T, typename Tint>
DelaunayPolyhedron<T, Tint>
erdahl_sub_polyhedron_of_face(ErdahlFunctionSpace<T> const &W,
                              DelaunayPolyhedron<T, Tint> const &D,
                              Face const &eFace,
                              ErdahlCanonicalHint<Tint> const *hint,
                              std::ostream &os) {
  MyMatrix<T> G = erdahl_function_of_face(W, D, eFace);
  DelaunayPolyhedron<T, Tint> Dsub =
      erdahl_polyhedron_extension<T, Tint>(W, G, D, true, hint, os);
#ifdef SANITY_CHECK_ERDAHL_POLYTOPE
  if (Dsub.EXT.rows() != static_cast<int>(eFace.count()) || Dsub.L.rows() > 0) {
    std::cerr << "ERDAHL: the zero set is not the face\n";
    throw TerminalException{1};
  }
  if (!erdahl_is_subset(Dsub, D)) {
    std::cerr << "ERDAHL: the sub-polyhedron is not contained in D\n";
    throw TerminalException{1};
  }
  if (erdahl_perfection_rank(W, Dsub) != erdahl_perfection_rank(W, D) + 1) {
    std::cerr << "ERDAHL: the sub-polyhedron does not have rank r+1\n";
    throw TerminalException{1};
  }
#endif
  return Dsub;
}

// clang-format off
#endif  // SRC_ERDAHL_ERDAHL_POLYTOPE_H_
// clang-format on
