// Copyright (C) 2026 Mathieu Dutour Sikiric <mathieu.dutour@gmail.com>
// clang-format off
#include "NumberTheoryBoostCppInt.h"
#include "NumberTheoryBoostGmpInt.h"
#include "NumberTheory.h"
#include "PeriodicDelaunay.h"
#include "Permutation.h"
#include "Group.h"
// clang-format on

/*
  A random admissible coset configuration of a periodic point set, the input
  PERIODIC_LookForRecordCovering consumes.

  The point set is Z^n + {0, c_2, ..., c_m} with the c_k drawn uniformly in
  (1/N)Z^n / Z^n. Two conditions have to hold for the configuration to be
  usable, and both are checked with the very predicates the enumeration
  applies rather than with a copy of them:

  * the cosets must not form a group modulo Z^n. They would then describe a
    lattice, which cannot beat the lattice record by construction, and which
    the periodic machinery rejects anyway (PeriodicPointSetFromRational_Opt).

  * the pointwise stabilizer of the T-space must stabilize the point set.
    For the classic GL_n(Z) T-space that stabilizer is generated by -I, so
    the condition is that -C is C modulo Z^n up to a translation, tested
    here by PeriodicAffineExtension. Configurations violating it are common
    -- {0, (1/3,0,0), (0,1/3,0)} is one -- and the enumeration refuses them,
    so drawing them here and dropping them is the cheap way to only ever
    hand out configurations that work.

  For another T-space, whose pointwise stabilizer is larger, a configuration
  produced here may still be refused; PERIODIC_LookForRecordCovering states
  which generator is at fault.

  Some (n, N, m) admit no configuration at all: with N = 2 every two-element
  set {0, c} is a group, c + c being 0 modulo Z^n. The program says so after
  exhausting its attempts rather than looping.
 */

template <typename T, typename Tint>
void process(int n, int N, int n_coset, int n_attempt,
             std::string const &FileOut) {
  // The cosets are drawn as integral numerators over the common denominator
  // N, which is the representation PeriodicPointSet uses.
  for (int i_attempt = 0; i_attempt < n_attempt; i_attempt++) {
    std::set<MyVector<Tint>> set_coset;
    MyVector<Tint> eZero = ZeroVector<Tint>(n);
    set_coset.insert(eZero);
    while (static_cast<int>(set_coset.size()) < n_coset) {
      MyVector<Tint> eV(n);
      for (int i = 0; i < n; i++) {
        eV(i) = Tint(random() % N);
      }
      set_coset.insert(eV);
    }
    MyMatrix<T> Cosets(n_coset, n);
    int pos = 0;
    for (auto &eV : set_coset) {
      for (int i = 0; i < n; i++) {
        Cosets(pos, i) = UniversalScalarConversion<T, Tint>(eV(i)) / T(N);
      }
      pos++;
    }
    std::optional<PeriodicPointSet<Tint>> opt_pps =
        PeriodicPointSetFromRational_Opt<Tint, T>(Cosets);
    if (!opt_pps) {
      // The cosets form a group: the point set is a lattice.
      continue;
    }
    PeriodicPointSet<Tint> const &pps = *opt_pps;
    MyMatrix<T> MinusIdentity = -IdentityMat<T>(n);
    if (!PeriodicAffineExtension<Tint, T>(pps, MinusIdentity)) {
      // -I does not preserve the point set, so the classic T-space cannot
      // be used with it.
      continue;
    }
    // The normalized cosets, which may carry a smaller denominator than the
    // N asked for: the normalization puts the first coset at the origin and
    // divides out the resulting common factor.
    T N_out = UniversalScalarConversion<T, Tint>(pps.N);
    MyMatrix<T> CosetsOut(pps.cosets_num.rows(), n);
    for (int k = 0; k < pps.cosets_num.rows(); k++) {
      for (int i = 0; i < n; i++) {
        CosetsOut(k, i) =
            UniversalScalarConversion<T, Tint>(pps.cosets_num(k, i)) / N_out;
      }
    }
    WriteMatrixFile(FileOut, CosetsOut);
    std::cerr << "PERIODIC_RANDOM: found a configuration after "
              << (i_attempt + 1) << " attempts, n_coset="
              << pps.cosets_num.rows() << " N=" << pps.N << "\n";
    std::cerr << "PERIODIC_RANDOM: wrote " << FileOut << "\n";
    return;
  }
  std::cerr << "PERIODIC_RandomCosets: no admissible configuration found for "
               "n="
            << n << " N=" << N << " n_coset=" << n_coset << " in " << n_attempt
            << " attempts. Either the parameters admit none (with N = 2 every "
               "two-element set of cosets is a group modulo Z^n, hence a "
               "lattice) or they are too tight; try another N or another "
               "number of cosets\n";
  throw TerminalException{1};
}

int main(int argc, char *argv[]) {
  maybe_install_gmp_pool();
  HumanTime time;
  try {
    if (argc != 6) {
      std::cerr << "Number of argument is = " << argc << "\n";
      std::cerr << "This program is used as\n";
      std::cerr << "PERIODIC_RandomCosets [n] [N] [n_coset] [n_attempt] "
                   "[FileOut]\n";
      std::cerr << "\n";
      std::cerr << "with:\n";
      std::cerr << "n         : the dimension\n";
      std::cerr << "N         : the denominator, the cosets being drawn in "
                   "(1/N)Z^n / Z^n\n";
      std::cerr << "n_coset   : the number of cosets, the zero one included\n";
      std::cerr << "n_attempt : how many draws to make before giving up\n";
      std::cerr << "FileOut   : the coset matrix, in the format the "
                   "FileCosets entries read\n";
      return -1;
    }
    unsigned seed = get_random_seed();
    std::cerr << "seed=" << seed << "\n";
    srand(seed);
    int n = ParseScalar<int>(argv[1]);
    int N = ParseScalar<int>(argv[2]);
    int n_coset = ParseScalar<int>(argv[3]);
    int n_attempt = ParseScalar<int>(argv[4]);
    std::string FileOut = argv[5];
    if (n < 1 || N < 2 || n_coset < 2 || n_attempt < 1) {
      std::cerr << "PERIODIC_RandomCosets: need n >= 1, N >= 2, n_coset >= 2 "
                   "and n_attempt >= 1\n";
      throw TerminalException{1};
    }
    using T = mpq_class;
    using Tint = mpz_class;
    process<T, Tint>(n, N, n_coset, n_attempt, FileOut);
    //
    std::cerr << "Normal termination of PERIODIC_RandomCosets\n";
  } catch (TerminalException const &e) {
    std::cerr << "Error in PERIODIC_RandomCosets\n";
    exit(e.eVal);
  }
  runtime(time);
}
