// Copyright (C) 2026 Mathieu Dutour Sikiric <mathieu.dutour@gmail.com>
// clang-format off
#include "NumberTheory.h"
#include "PeriodicDelaunay.h"
#include "Permutation.h"
#include "Group.h"
// clang-format on

/*
  The stabilizer and the equivalence of Gram matrices under the
  transformations preserving a periodic point set, checked on the point set
  Z^2 + {(0,0), (1/3,0)} in the T-space of all the symmetric matrices,
  where every group involved is small enough to be verified by hand:

  --- for the identity form, the automorphism group is the dihedral group
  of order 8 and the coset-adequate subgroup has order 4: the diagonal
  sign matrices are adequate (-1 on the first axis is repaired by the
  translation by the coset), the swaps are not, since they move the coset
  to (0, 1/3) which no translation brings back.
  --- for the generic form [[1,1/7],[1/7,1]] the automorphism group is
  {+-Id, +-Swap} of order 4 and the adequate subgroup is {+-Id} of order 2.
  --- the equivalence with the diagonal-sign transformed form exists, the
  one with the shear transformed form exists in the lattice sense but not
  in the periodic sense: no automorphism can repair the shear.
 */

using T = mpq_class;
using Tring = mpz_class;
using Tint = mpz_class;
using Tidx = uint32_t;
using Telt = permutalib::SingleSidedPerm<Tidx>;
using Tint_grp = mpz_class;
using Tgroup = permutalib::Group<Telt, Tint_grp>;

void check(bool test, std::string const &context) {
  if (!test) {
    std::cerr << "TEST_PeriodicTspaceStabEqui failed: " << context << "\n";
    throw TerminalException{1};
  }
}

// The order of the group generated by a set of matrices, by closure. The
// groups of the test have order at most 8.
size_t GroupOrderByClosure(std::vector<MyMatrix<T>> const &ListGen, int n) {
  std::vector<MyMatrix<T>> ListElt{IdentityMat<T>(n)};
  auto f_insert = [&](MyMatrix<T> const &M) -> bool {
    for (auto &eElt : ListElt) {
      if (eElt == M) {
        return false;
      }
    }
    ListElt.push_back(M);
    return true;
  };
  while (true) {
    bool DoSomething = false;
    std::vector<MyMatrix<T>> ListCur = ListElt;
    for (auto &eElt : ListCur) {
      for (auto &eGen : ListGen) {
        if (f_insert(eElt * eGen)) {
          DoSomething = true;
        }
      }
    }
    if (!DoSomething) {
      break;
    }
  }
  return ListElt.size();
}

size_t StabilizerOrder(LinSpaceMatrix<T> const &LinSpa,
                       std::optional<PeriodicPointSet<Tring>> const &opt_pps,
                       MyMatrix<T> const &eMat, std::ostream &os) {
  MyMatrix<Tint> SHV = ExtractInvariantVectorFamilyZbasis<T, Tint>(eMat, os);
  MyMatrix<T> SHV_T = UniversalMatrixConversion<T, Tint>(SHV);
  std::optional<MyMatrix<T>> CommonGramMat;
  auto get_result = [&]() -> Result_ComputeStabilizer_SHV<T, Tgroup> {
    if (opt_pps) {
      return LINSPA_ComputeStabilizer_SHV_Periodic<T, Tring, Tgroup>(
          LinSpa, *opt_pps, eMat, SHV_T, CommonGramMat, os);
    }
    return LINSPA_ComputeStabilizer_SHV<T, Tgroup>(LinSpa, eMat, SHV_T,
                                                   CommonGramMat, os);
  };
  Result_ComputeStabilizer_SHV<T, Tgroup> res = get_result();
  std::vector<MyMatrix<T>> ListGen =
      res.get_list_matrix(SHV_T, eMat, LinSpa, os);
  return GroupOrderByClosure(ListGen, eMat.rows());
}

std::optional<MyMatrix<T>>
Equivalence(LinSpaceMatrix<T> const &LinSpa,
            std::optional<PeriodicPointSet<Tring>> const &opt_pps,
            MyMatrix<T> const &eMat1, MyMatrix<T> const &eMat2,
            std::ostream &os) {
  MyMatrix<Tint> SHV1 = ExtractInvariantVectorFamilyZbasis<T, Tint>(eMat1, os);
  MyMatrix<Tint> SHV2 = ExtractInvariantVectorFamilyZbasis<T, Tint>(eMat2, os);
  MyMatrix<T> SHV1_T = UniversalMatrixConversion<T, Tint>(SHV1);
  MyMatrix<T> SHV2_T = UniversalMatrixConversion<T, Tint>(SHV2);
  std::optional<MyMatrix<T>> CommonGramMat;
  if (opt_pps) {
    return LINSPA_TestEquivalenceGramMatrix_SHV_Periodic<T, Tring, Tgroup>(
        LinSpa, *opt_pps, eMat1, eMat2, SHV1_T, SHV2_T, CommonGramMat, os);
  }
  return LINSPA_TestEquivalenceGramMatrix_SHV<T, Tgroup>(
      LinSpa, eMat1, eMat2, SHV1_T, SHV2_T, CommonGramMat, os);
}

int main() {
  HumanTime time;
  try {
    std::ostream &os = std::cerr;
    int n = 2;
    MyMatrix<T> Cosets(2, n);
    Cosets(0, 0) = 0;
    Cosets(0, 1) = 0;
    Cosets(1, 0) = T(1) / T(3);
    Cosets(1, 1) = 0;
    PeriodicPointSet<Tring> pps = PeriodicPointSetFromRational<Tring>(Cosets);
    std::optional<PeriodicPointSet<Tring>> opt_pps{pps};
    std::optional<PeriodicPointSet<Tring>> no_pps;
    LinSpaceMatrix<T> LinSpa = ComputeCanonicalSpace<T>(n);
    std::cerr << "|PtStabGens|=" << LinSpa.PtStabGens.size() << "\n";
    // The experiment behind the design: the generators of the pointwise
    // stabilizer have to be coset-adequate. For the full symmetric space
    // this is {+-Id}, adequate thanks to the translation repair.
    size_t n_adequate = 0;
    for (auto &eGen : LinSpa.PtStabGens) {
      if (PeriodicAffineExtension<Tring, T>(pps, eGen)) {
        n_adequate++;
      }
    }
    std::cerr << "|adequate PtStabGens|=" << n_adequate << "\n";
    check(n_adequate == LinSpa.PtStabGens.size(),
          "every generator of the pointwise stabilizer is coset adequate");
    // The adequacy of single linear parts, all verified by hand.
    auto is_adequate = [&](MyMatrix<T> const &M) -> bool {
      return PeriodicAffineExtension<Tring, T>(pps, M).has_value();
    };
    MyMatrix<T> MinusId = -IdentityMat<T>(n);
    MyMatrix<T> Swap = ZeroMatrix<T>(n, n);
    Swap(0, 1) = 1;
    Swap(1, 0) = 1;
    MyMatrix<T> Shear = IdentityMat<T>(n);
    Shear(0, 1) = 1;
    check(is_adequate(MinusId), "-Id is adequate through the translation");
    check(!is_adequate(Swap), "the swap is not adequate");
    check(!is_adequate(Shear), "the shear is not adequate");
    // The stabilizers, plain and periodic.
    MyMatrix<T> IdMat = IdentityMat<T>(n);
    size_t ord_id_plain = StabilizerOrder(LinSpa, no_pps, IdMat, os);
    size_t ord_id_per = StabilizerOrder(LinSpa, opt_pps, IdMat, os);
    std::cerr << "identity form: |stab|=" << ord_id_plain
              << " |periodic stab|=" << ord_id_per << "\n";
    check(ord_id_plain == 8, "the automorphism group of Id has order 8");
    check(ord_id_per == 4, "the coset adequate subgroup has order 4");
    MyMatrix<T> Gen(n, n);
    Gen(0, 0) = 1;
    Gen(0, 1) = T(1) / T(7);
    Gen(1, 0) = T(1) / T(7);
    Gen(1, 1) = 1;
    size_t ord_gen_plain = StabilizerOrder(LinSpa, no_pps, Gen, os);
    size_t ord_gen_per = StabilizerOrder(LinSpa, opt_pps, Gen, os);
    std::cerr << "generic form: |stab|=" << ord_gen_plain
              << " |periodic stab|=" << ord_gen_per << "\n";
    check(ord_gen_plain == 4, "the automorphism group of Gen has order 4");
    check(ord_gen_per == 2, "the coset adequate subgroup is {+-Id}");
    // The equivalences. The diagonal sign matrix is adequate and maps Gen
    // to GenD, so the periodic equivalence exists. The shear maps Gen to
    // GenS and no automorphism of Gen repairs its coset failure, so the
    // lattice equivalence exists and the periodic one does not.
    MyMatrix<T> DiagSign = IdentityMat<T>(n);
    DiagSign(1, 1) = -1;
    MyMatrix<T> GenD = DiagSign * Gen * DiagSign.transpose();
    MyMatrix<T> GenS = Shear * Gen * Shear.transpose();
    auto check_equiv = [&](std::optional<MyMatrix<T>> const &opt,
                           MyMatrix<T> const &eMat2, bool expected,
                           std::string const &context) -> void {
      check(opt.has_value() == expected, context);
      if (opt) {
        MyMatrix<T> const &M = *opt;
        check(M * Gen * M.transpose() == eMat2,
              "the equivalence maps the first form to the second");
      }
    };
    check_equiv(Equivalence(LinSpa, no_pps, Gen, GenD, os), GenD, true,
                "the lattice equivalence with GenD exists");
    std::optional<MyMatrix<T>> optD = Equivalence(LinSpa, opt_pps, Gen, GenD, os);
    check_equiv(optD, GenD, true, "the periodic equivalence with GenD exists");
    check(PeriodicAffineExtension<Tring, T>(pps, *optD).has_value(),
          "the periodic equivalence is coset adequate");
    check_equiv(Equivalence(LinSpa, no_pps, Gen, GenS, os), GenS, true,
                "the lattice equivalence with GenS exists");
    check_equiv(Equivalence(LinSpa, opt_pps, Gen, GenS, os), GenS, false,
                "the periodic equivalence with GenS does not exist");
    std::cerr << "Normal termination of TEST_PeriodicTspaceStabEqui\n";
  } catch (TerminalException const &e) {
    std::cerr << "Erroneous termination of TEST_PeriodicTspaceStabEqui\n";
    exit(e.eVal);
  }
  runtime(time);
}
