// Copyright (C) 2022 Mathieu Dutour Sikiric <mathieu.dutour@gmail.com>
#ifndef SRC_GROUP_MATRIXGROUPAVERAGE_H_
#define SRC_GROUP_MATRIXGROUPAVERAGE_H_

// clang-format off
#include "MAT_Matrix.h"
#include <vector>
// clang-format on

#ifdef DEBUG
#define DEBUG_MATRIX_GROUP_AVERAGE
#endif

#ifdef DISABLE_DEBUG_MATRIX_GROUP_AVERAGE
#undef DEBUG_MATRIX_GROUP_AVERAGE
#endif

/*
  Builds the smallest vector space containing the space TheBasis and invariant
  by the group generated by LGen. Code adapted from DirectSpannEquivariantSpace
  in the GAP version.
  ---
  The MutableSubspaceBelongingRepetitive was designed for that goal and seems
  to work out fine and seem to be optimal.
 */
template <typename T>
MyMatrix<T> DirectSpannEquivariantSpace(MyMatrix<T> const &TheBasis,
                                        std::vector<MyMatrix<T>> const &LGen) {
  int dim = TheBasis.cols();
  MutableSubspaceBelongingRepetitive<T> msbr(dim);
  msbr.InsertMatrix(TheBasis);
  size_t pos_start = 0;
  size_t pos_end = msbr.get_n_vect();
  MyVector<T> V(dim);
#ifdef DEBUG_MATRIX_GROUP_AVERAGE
  int n_iter = 0;
#endif
  while (true) {
    if (pos_start == pos_end) {
      break;
    }
    for (size_t pos = pos_start; pos < pos_end; pos++) {
      msbr.SetVectout(pos, V);
      for (auto &eGen : LGen) {
        MyVector<T> Vimg = eGen.transpose() * V;
        (void)msbr.InsertVector(Vimg);
      }
    }
    pos_start = pos_end;
    pos_end = msbr.get_n_vect();
#ifdef DEBUG_MATRIX_GROUP_AVERAGE
    n_iter += 1;
    std::cerr << "GA n_iter=" << n_iter << " pos_start=" << pos_start
              << " pos_end=" << pos_end << "\n";
#endif
  }
  return msbr.GetBasis();
}

/*
  The orbit averaging operator P = (1/|G|) sum_{g in G} g^T is the linear
  projection onto the invariant subspace Fix(G) = { v : g^T v = v for all g }
  along the augmentation subspace W = span{ (g^T - I) v : g in G, v in V }. Rather
  than averaging one specific vector (which, over jets, would divide by a zero
  divisor whenever that vector is invariant at t = 0, since the differences
  g^T v - v are then O(t) with a vanishing leading coefficient), we build P once
  from the action of the generators on the fixed standard basis:
    - Fix(G) is the right nullspace of the stacked (g^T - I)  -- the rows v with
      (g^T - I) v = 0 for every generator;
    - W is the row space of the stacked (g - I), which equals the column space of
      the (g^T - I), i.e. span{ (g^T - I) e_i }. Using generators suffices: the
      orthogonal complement of that span is exactly Fix(G).
  By Maschke's theorem (finite group, characteristic 0) V = Fix(G) (+) W, so
  B = [Fix | W] is a basis and P is the projector sending the Fix part of each
  vector to itself and the W part to 0: P = [Fix | 0] B^{-1}. Everything here is
  built from the (constant, integer) group action on fixed basis vectors, never
  from the jet vector being averaged, so for a jet scalar T the data is
  t-independent (constant jets) and no division by a zero divisor occurs. The
  orbit barycenter of any vector a is then P * a.
 */
template <typename T>
MyMatrix<T> OrbitAveragingProjection(int dim,
                                     std::vector<MyMatrix<T>> const &LGen) {
  MyMatrix<T> Id = IdentityMat<T>(dim);
  if (LGen.empty())
    return Id;
  int m = LGen.size();
  MyMatrix<T> FixStack(m * dim, dim); // stacked (g^T - I): its nullspace is Fix
  MyMatrix<T> WStack(m * dim, dim);   // stacked (g - I): its row space is W
  for (int j = 0; j < m; j++) {
    MyMatrix<T> gT_minus_I = LGen[j].transpose() - Id;
    MyMatrix<T> g_minus_I = LGen[j] - Id;
    for (int r = 0; r < dim; r++)
      for (int c = 0; c < dim; c++) {
        FixStack(j * dim + r, c) = gT_minus_I(r, c);
        WStack(j * dim + r, c) = g_minus_I(r, c);
      }
  }
  // NullspaceTrMat(A) is the right nullspace { v : A v = 0 } (rows of length
  // A.cols()), which is exactly Fix(G) = { v : (g^T - I) v = 0 for all g }.
  MyMatrix<T> Fix_rows = NullspaceTrMat(FixStack); // Fix basis (f x dim)
  MyMatrix<T> W_rows = RowReduction(WStack); // W basis (w x dim), f + w = dim
  int w = W_rows.rows();
  // B^T = [Fix ; W] (rows), and [Fix | 0]^T = [Fix ; 0]. Then
  // P^T = (B^T)^{-1} [Fix | 0]^T, so P = transpose of that.
  MyMatrix<T> C = Concatenate(Fix_rows, W_rows);
  MyMatrix<T> D = Concatenate(Fix_rows, ZeroMatrix<T>(w, dim));
  MyMatrix<T> Pt = Inverse(C) * D;
  MyMatrix<T> P = Pt.transpose();
#ifdef SANITY_CHECK_MATRIX_GROUP_AVERAGE
  // P must be a projection (P^2 = P) absorbing the group action (g^T P = P).
  if (P * P != P) {
    std::cerr << "MATRIX_GROUP_AVERAGE: P is not idempotent\n";
    throw TerminalException{1};
  }
  for (auto &eGen : LGen)
    if (eGen.transpose() * P != P) {
      std::cerr << "MATRIX_GROUP_AVERAGE: g^T P != P\n";
      throw TerminalException{1};
    }
#endif
  return P;
}

/*
  Compute the average of a vector under the group generated by the generators,
  as the orbit averaging projection applied to the vector (see above). The
  projection is built from the constant group only, so this is division-free
  over jets.
 */
template <typename T>
MyVector<T> OrbitBarycenter(MyVector<T> const &a,
                            std::vector<MyMatrix<T>> const &LGen) {
  MyMatrix<T> P = OrbitAveragingProjection<T>(a.size(), LGen);
  MyVector<T> TheSol = P * a;
#ifdef DEBUG_MATRIX_GROUP_AVERAGE
  for (auto &eGen : LGen) {
    MyVector<T> img = eGen.transpose() * TheSol;
    if (img != TheSol) {
      std::cerr << "GA: OrbitBarycenter result is not invariant\n";
      throw TerminalException{1};
    }
  }
#endif
  return TheSol;
}

/*
  Now doing it over the action of the group over symmetric matrices by
  M -> g M g^T
 */
template <typename T>
MyMatrix<T>
OrbitBarycenterSymmetricMatrix(MyMatrix<T> const &M,
                               std::vector<MyMatrix<T>> const &LGen) {
  int n = M.rows();
  int sym_dim = (n * (n + 1)) / 2;
  MyVector<T> a(sym_dim);
  MyMatrix<int> C(sym_dim, 2);
  MyMatrix<int> Crev(n, n);
  int off_dim = (n * (n - 1)) / 2;
  std::vector<int> LOff(off_dim);
  int pos_sym = 0;
  int pos_off = 0;
  for (int i = 0; i < n; i++) {
    for (int j = i; j < n; j++) {
      a(pos_sym) = M(i, j);
      C(pos_sym, 0) = i;
      C(pos_sym, 1) = j;
      Crev(i, j) = pos_sym;
      Crev(j, i) = pos_sym;
      if (i != j) {
        LOff[pos_off] = pos_sym;
        pos_off++;
      }
      pos_sym++;
    }
  }
  MyMatrix<int> LHalf(off_dim, 2);
  int pos = 0;
  for (int i = 0; i < n; i++) {
    for (int j = i + 1; j < n; j++) {
      LHalf(pos, 0) = i;
      LHalf(pos, 1) = j;
      pos++;
    }
  }
  std::vector<MyMatrix<T>> LGenExt;
  for (auto &eGen : LGen) {
    MyMatrix<T> eGenExt = ZeroMatrix<T>(sym_dim, sym_dim);
    for (int i_sym = 0; i_sym < sym_dim; i_sym++) {
      int i = C(i_sym, 0);
      int j = C(i_sym, 1);
      // A matrix entry with 1 in position (i,j) and (j,i)
      //
      // We need to Compute the products
      // P E_{i,i} P^T and
      // P (E_{i,j} + E_{j,i}) P^T
      //
      // Let us compute the initial product
      // P E_{i,j} P^T
      // First the product P E_{i,j}
      // It is a n x n matrix with the i-th column of P in the column j;
      // The product P E_{i,j} P^T is
      // [p_{k,i} p_{l,j}]_{1 \leq k,l \leq n}
      // k is row and l is the column.
      for (int k = 0; k < n; k++) {
        for (int l = 0; l < n; l++) {
          int pos = Crev(k, l);
          AddMul(eGenExt(i_sym, pos), eGen(k, i), eGen(l, j));
          if (i != j) {
            AddMul(eGenExt(i_sym, pos), eGen(k, j), eGen(l, i));
          }
        }
      }
    }
    for (int i_off = 0; i_off < off_dim; i_off++) {
      int pos_sym = LOff[i_off];
      for (int i_sym = 0; i_sym < sym_dim; i_sym++) {
        eGenExt(i_sym, pos_sym) /= 2;
      }
    }
    LGenExt.push_back(eGenExt);
  }
  MyVector<T> a_bary = OrbitBarycenter(a, LGenExt);
  MyMatrix<T> M_bary(n, n);
  int pos_sym_b = 0;
  for (int i = 0; i < n; i++) {
    for (int j = i; j < n; j++) {
      M_bary(i, j) = a_bary(pos_sym_b);
      M_bary(j, i) = a_bary(pos_sym_b);
      pos_sym_b++;
    }
  }
#ifdef DEBUG_MATRIX_GROUP_AVERAGE
  for (auto &eGen : LGen) {
    MyMatrix<T> Mimg = eGen * M_bary * eGen.transpose();
    if (Mimg != M_bary) {
      std::cerr << "GA: Failed to find an invariant matrix. Clear bug\n";
      throw TerminalException{1};
    }
  }
#endif
  return M_bary;
}

// clang-format off
#endif  // SRC_GROUP_MATRIXGROUPAVERAGE_H_
// clang-format on
