// Copyright (C) 2026 Mathieu Dutour Sikiric <mathieu.dutour@gmail.com>
#ifndef SRC_LATT_BKZ_H_
#define SRC_LATT_BKZ_H_
// clang-format off
#include "ClassicLLL.h"
#include "DeepLLL.h"
#include "MAT_Matrix.h"
#include "MAT_MatrixInt.h"
#include "Shvec_exact.h"
#include <string>
#include <utility>
#include <vector>
// clang-format on

#ifdef DEBUG
#define DEBUG_BKZ
#endif

#ifdef DISABLE_DEBUG_BKZ
#undef DEBUG_BKZ
#endif

#ifdef SANITY_CHECK
#define SANITY_CHECK_BKZ
#endif

#ifdef TIMINGS
#define TIMINGS_BKZ
#endif

/*
  BKZ, block Korkine-Zolotarev reduction.

  Write pi_j for the orthogonal projection onto the complement of
  span(b_1, ..., b_{j-1}), so pi_j(b_j) = b_j^*, and for a block size beta put
  k = min(j + beta - 1, n) and

      L_[j,k] = the lattice generated by pi_j(b_j), ..., pi_j(b_k),

  of rank at most beta. A basis is BKZ-beta reduced when it is size reduced
  and, for every j, b_j^* is a SHORTEST non-zero vector of L_[j,k].

  beta = 2 gives the Lovasz condition, that is LLL; beta = n gives
  Hermite-Korkine-Zolotarev. So beta is one dial between a cheap local
  condition and an expensive global one.

  What changes relative to the other reductions in this package is neither the
  move set, as for deep insertion, nor the objective, as for Seysen, but the
  ORACLE. The question asked at each index is no longer a comparison of two
  quantities already at hand but a shortest-vector problem, solved exactly, in
  dimension beta. That is what makes BKZ strictly stronger than either, and
  also what makes it cost what it costs: the enumeration is beta^O(beta), so
  beta is a dial and not a setting.

  THE BLOCK IS OBTAINED BY BAREISS ELIMINATION, INCREMENTALLY. The Gram matrix
  of pi_j(b_j), ..., pi_j(b_k) is a Schur complement and therefore rational,
  but scaled by d_j = det of the leading j x j minor it is integral: it is
  exactly what j steps of the fraction-free elimination leave in the trailing
  block, since after those steps the entry (a,b) is the determinant of the
  submatrix on rows and columns {1..j-1, a} and {1..j-1, b}, which equals
  d_j <pi_j(b_a), pi_j(b_b)>. Advancing j by one costs one more elimination
  step, so a whole tour extracts all its blocks in O(n^3) rather than
  recomputing each from scratch. A shortest vector is unchanged by a positive
  rescaling of the form, so the enumerator runs on the scaled matrix directly
  and the comparison against delta |b_j^*|^2, which is the scaled entry
  work(j,j), is again a comparison of two integers.

  TERMINATION is the argument of deep insertion rather than of LLL. An accepted
  insertion at position j leaves the leading principal minors D_1, ..., D_{j-1}
  unchanged, strictly decreases D_j -- the new j-th Gram-Schmidt norm being the
  shortest vector found, below delta |b_j^*|^2 -- and says nothing about the
  minors strictly between j and k. The classical product potential therefore
  need not decrease. What does is the vector (D_1, ..., D_{n-1}) in the
  lexicographic order, which over the positive integers is well founded. The
  intervening LLL passes never increase any D_i, an LLL swap at index k
  changing only D_{k-1} and decreasing it, so they do not disturb the argument.
  Hence the algorithm terminates on an integral form. As for deep insertion the
  bound is exponential, and no polynomial bound on the number of tours is
  known.

  References: C. P. Schnorr, A hierarchy of polynomial time lattice basis
  reduction algorithms, Theoret. Comput. Sci. 53 (1987) 201--224; C. P.
  Schnorr, M. Euchner, Lattice basis reduction: improved practical algorithms
  and solving subset sum problems, Math. Programming 66 (1994) 181--199.
 */

/*
  One step of the fraction-free elimination on the trailing block. On entry
  work(a,b) for a,b >= j is d_j <pi_j(b_a), pi_j(b_b)>; on exit the same holds
  for j+1, and prev carries the pivot needed by the Bareiss division.
 */
template <typename Tring>
void BKZ_BareissStep(MyMatrix<Tring> &work, int const &j, Tring &prev) {
  int n = work.rows();
  Tring pivot = work(j, j);
  for (int a = j + 1; a < n; a++) {
    for (int b = j + 1; b < n; b++) {
      Tring num = work(a, b) * pivot - work(a, j) * work(j, b);
      Tring quot = num / prev;
#ifdef SANITY_CHECK_BKZ
      if (quot * prev != num) {
        std::cerr << "BKZ: non-exact Bareiss division, the form is not "
                     "integral over an integral domain\n";
        throw TerminalException{1};
      }
#endif
      work(a, b) = quot;
    }
  }
  prev = pivot;
}

/*
  The unimodular transformation inserting sum_i z_i b_i at position j, the
  block running from j to k. The coefficient vector returned by the enumerator
  is primitive -- were its entries to share a factor g, dividing by g would give
  a shorter vector of the block lattice -- so it extends to a basis, and
  ComplementToBasis supplies the extension. The inserted vector is put first so
  that it lands at position j; the rest of the block is whatever completes it,
  the following LLL pass being what tidies that up.
 */
/*
  The scaled projected block Gram matrix of the indices j, ..., j+m-1, that is
  d_j times the Gram matrix of pi_j(b_j), ..., pi_j(b_{j+m-1}). Obtained by
  running the fraction-free elimination for j steps and reading the trailing
  block; see the head of this file. A caller sweeping j upwards should instead
  keep one working matrix and call BKZ_BareissStep, which is what the descent
  does; this form is for a caller that needs one block in isolation.
 */
template <typename Tring>
MyMatrix<Tring> BKZ_ProjectedBlockGram(MyMatrix<Tring> const &gram,
                                       int const &j, int const &m) {
  MyMatrix<Tring> work = gram;
  Tring prev(1);
  for (int i = 0; i < j; i++) {
    BKZ_BareissStep(work, i, prev);
  }
  MyMatrix<Tring> blk(m, m);
  for (int a = 0; a < m; a++) {
    for (int b = 0; b < m; b++) {
      blk(a, b) = work(j + a, j + b);
    }
  }
  return blk;
}

/*
  A unimodular matrix whose first row is the primitive vector z.
  ComplementToBasis returns c_1, ..., c_{m-1} with (c_1, ..., c_{m-1}, z) a
  basis; putting z first only changes the determinant by a sign.
 */
template <typename Tint>
MyMatrix<Tint> BKZ_UnimodularWithFirstRow(MyVector<Tint> const &z) {
  int m = z.size();
#ifdef SANITY_CHECK_BKZ
  if (!IsVectorPrimitive(z)) {
    std::cerr << "BKZ: BKZ_UnimodularWithFirstRow needs a primitive vector\n";
    throw TerminalException{1};
  }
#endif
  MyMatrix<Tint> compl_mat = ComplementToBasis(z);
  MyMatrix<Tint> U(m, m);
  for (int c = 0; c < m; c++) {
    U(0, c) = z(c);
  }
  for (int r = 0; r + 1 < m; r++) {
    for (int c = 0; c < m; c++) {
      U(r + 1, c) = compl_mat(r, c);
    }
  }
#ifdef SANITY_CHECK_BKZ
  Tint det_U = DeterminantMat(U);
  if (det_U != 1 && det_U != -1) {
    std::cerr << "BKZ: BKZ_UnimodularWithFirstRow produced a non-unimodular "
                 "matrix, det="
              << det_U << "\n";
    throw TerminalException{1};
  }
#endif
  return U;
}

/*
  Apply an m x m unimodular transformation to the block starting at j, on the
  Gram matrix and on the accumulated transformation together.
 */
template <typename Tring, typename Tint>
void BKZ_ApplyBlockTransformation(MyMatrix<Tring> &gram, MyMatrix<Tint> &H,
                                  MyMatrix<Tint> const &U_blk, int const &j) {
  int n = gram.rows();
  int m = U_blk.rows();
  MyMatrix<Tint> U = IdentityMat<Tint>(n);
  for (int a = 0; a < m; a++) {
    for (int b = 0; b < m; b++) {
      U(j + a, j + b) = U_blk(a, b);
    }
  }
  MyMatrix<Tring> U_r = UniversalMatrixConversion<Tring, Tint>(U);
  gram = U_r * gram * U_r.transpose();
  H = U * H;
}

template <typename Tint>
MyMatrix<Tint> BKZ_InsertionMatrix(MyVector<Tint> const &z, int const &n,
                                   int const &j, int const &k) {
  int m = k - j + 1;
#ifdef SANITY_CHECK_BKZ
  if (z.size() != m) {
    std::cerr << "BKZ: the coefficient vector has size " << z.size()
              << " but the block has size " << m << "\n";
    throw TerminalException{1};
  }
  if (!IsVectorPrimitive(z)) {
    std::cerr << "BKZ: the enumerator returned a non-primitive coefficient "
                 "vector, which a shortest vector cannot be\n";
    throw TerminalException{1};
  }
#endif
  MyMatrix<Tint> U_blk = BKZ_UnimodularWithFirstRow(z);
  MyMatrix<Tint> U = IdentityMat<Tint>(n);
  for (int a = 0; a < m; a++) {
    for (int b = 0; b < m; b++) {
      U(j + a, j + b) = U_blk(a, b);
    }
  }
#ifdef SANITY_CHECK_BKZ
  Tint det_U = DeterminantMat(U);
  if (det_U != 1 && det_U != -1) {
    std::cerr << "BKZ: the insertion matrix is not unimodular, det=" << det_U
              << "\n";
    throw TerminalException{1};
  }
#endif
  return U;
}

/*
  BKZ-beta with the slack delta = delta_num / delta_den.

  max_tour caps the number of tours; 0 means no cap. An early abort costs
  little quality in practice, most of the gain arriving in the first few tours,
  and it is the standard guard against the absence of a polynomial bound.
 */
template <typename T, typename Tint>
LLLreduction<T, Tint> BKZreducedBasisDelta(MyMatrix<T> const &GramMat,
                                           int const &beta,
                                           int const &delta_num,
                                           int const &delta_den,
                                           int const &max_tour,
                                           std::ostream &os) {
  using Tring = typename underlying_ring<T>::ring_type;
  int n = GramMat.rows();
#ifdef SANITY_CHECK_BKZ
  if (n != GramMat.cols()) {
    std::cerr << "BKZ: The matrix should be square\n";
    throw TerminalException{1};
  }
  if (!IsSymmetricMatrix(GramMat)) {
    std::cerr << "BKZ: The Gram matrix should be symmetric\n";
    throw TerminalException{1};
  }
  if (beta < 2) {
    std::cerr << "BKZ: the block size must be at least 2, got " << beta
              << "\n";
    throw TerminalException{1};
  }
  if (delta_num <= 0 || delta_den <= 0 || delta_num > delta_den) {
    std::cerr << "BKZ: delta must lie in (0,1], got " << delta_num << "/"
              << delta_den << "\n";
    throw TerminalException{1};
  }
#endif
  if (n <= 1) {
    return {GramMat, IdentityMat<Tint>(n)};
  }
#ifdef SANITY_CHECK_BKZ
  if (!IsPositiveDefinite(GramMat, os)) {
    std::cerr << "BKZ: The BKZ reduction needs a positive definite matrix\n";
    throw TerminalException{1};
  }
#endif
#ifdef TIMINGS_BKZ
  MicrosecondTime time;
#endif
  // BKZ starts from an LLL reduced basis and restores that reduction after
  // every insertion: the block condition is stated about a basis, and the
  // enumeration is far cheaper on a reduced block than on a skewed one.
  LLLreduction<T, Tint> lll = LLLreducedBasis<T, Tint>(GramMat, os);
  MyMatrix<Tint> H = lll.Pmat;
  MyMatrix<Tring> gram = UniversalMatrixConversion<Tring, T>(
      RemoveFractionMatrix(lll.GramMatRed));
  Tring const num(delta_num);
  Tring const den(delta_den);
  [[maybe_unused]] size_t n_insert = 0;
  int n_tour = 0;
  while (true) {
    bool did_insert = false;
    MyMatrix<Tring> work = gram;
    Tring prev(1);
    for (int j = 0; j + 1 < n; j++) {
      int k = j + beta - 1;
      if (k > n - 1) {
        k = n - 1;
      }
      int m = k - j + 1;
      // The scaled projected block Gram matrix, read off the trailing block.
      MyMatrix<T> Gblock(m, m);
      for (int a = 0; a < m; a++) {
        for (int b = 0; b < m; b++) {
          Gblock(a, b) = UniversalScalarConversion<T, Tring>(work(j + a, j + b));
        }
      }
      Tshortest<T, Tint> shv = T_ShortestVector<T, Tint>(Gblock, os);
      Tring min_r = UniversalScalarConversion<Tring, T>(shv.min);
      // The same scaling d_j applies to the enumerated norm and to
      // work(j,j) = d_j |b_j^*|^2, so it cancels from the comparison.
      if (den * min_r < num * work(j, j)) {
        MyVector<Tint> z = GetMatrixRow(shv.SHV, 0);
        MyMatrix<Tint> U = BKZ_InsertionMatrix(z, n, j, k);
        MyMatrix<Tring> U_r = UniversalMatrixConversion<Tring, Tint>(U);
        gram = U_r * gram * U_r.transpose();
        H = U * H;
        // Restore the reduction: the inserted vector is generally not size
        // reduced against its predecessors, and the rest of the block is
        // whatever completed it.
        MyMatrix<T> gram_T = UniversalMatrixConversion<T, Tring>(gram);
        LLLreduction<T, Tint> step = LLLreducedBasis<T, Tint>(gram_T, os);
        gram = UniversalMatrixConversion<Tring, T>(
            RemoveFractionMatrix(step.GramMatRed));
        H = step.Pmat * H;
        n_insert++;
        did_insert = true;
        break;
      }
      BKZ_BareissStep(work, j, prev);
    }
    n_tour++;
    if (!did_insert) {
      break;
    }
    if (max_tour > 0 && n_tour >= max_tour) {
#ifdef DEBUG_BKZ
      os << "BKZ: early abort after " << n_tour << " tours\n";
#endif
      break;
    }
  }
#ifdef DEBUG_BKZ
  os << "BKZ: n=" << n << " beta=" << beta << " tours=" << n_tour
     << " insertions=" << n_insert << "\n";
#endif
  MyMatrix<T> P_T = UniversalMatrixConversion<T, Tint>(H);
  MyMatrix<T> GramMatRed = P_T * GramMat * P_T.transpose();
  LLLreduction<T, Tint> res = {std::move(GramMatRed), std::move(H)};
#ifdef SANITY_CHECK_BKZ
  CheckLLLreduction(res, GramMat);
#endif
#ifdef TIMINGS_BKZ
  os << "BKZ: BKZreducedBasisDelta beta=" << beta << " took " << time << "\n";
#endif
  return res;
}

/*
  The same delta as the classic reduction of this package, and no cap on the
  number of tours.
 */
template <typename T, typename Tint>
LLLreduction<T, Tint> BKZreducedBasis(MyMatrix<T> const &GramMat,
                                      int const &beta, std::ostream &os) {
  return BKZreducedBasisDelta<T, Tint>(GramMat, beta, 99, 100, 0, os);
}

/*
  Tests that a Gram matrix is BKZ-beta reduced: LLL reduced, and with every
  b_j^* a shortest vector of its block up to the slack delta. Recomputes
  everything from the matrix, so it is an independent check of a descent and
  not a restatement of it.
 */
template <typename T, typename Tint>
bool IsBKZreduced(MyMatrix<T> const &GramMat, int const &beta,
                  int const &delta_num, int const &delta_den,
                  std::ostream &os) {
  using Tring = typename underlying_ring<T>::ring_type;
  int n = GramMat.rows();
  if (n <= 1) {
    return true;
  }
  // LLL reducedness only: the deep condition at i = 0 is a strictly stronger
  // demand that BKZ at small block size does not make.
  if (!IsLLLreduced(GramMat, delta_num, delta_den, os)) {
    os << "BKZ: the basis is not even LLL reduced\n";
    return false;
  }
  MyMatrix<Tring> work =
      UniversalMatrixConversion<Tring, T>(RemoveFractionMatrix(GramMat));
  Tring prev(1);
  Tring const num(delta_num);
  Tring const den(delta_den);
  for (int j = 0; j + 1 < n; j++) {
    int k = j + beta - 1;
    if (k > n - 1) {
      k = n - 1;
    }
    int m = k - j + 1;
    MyMatrix<T> Gblock(m, m);
    for (int a = 0; a < m; a++) {
      for (int b = 0; b < m; b++) {
        Gblock(a, b) = UniversalScalarConversion<T, Tring>(work(j + a, j + b));
      }
    }
    Tshortest<T, Tint> shv = T_ShortestVector<T, Tint>(Gblock, os);
    Tring min_r = UniversalScalarConversion<Tring, T>(shv.min);
    if (den * min_r < num * work(j, j)) {
      os << "BKZ: the block condition fails at j=" << j << ", the block has a "
         << "vector of scaled norm " << min_r << " against " << work(j, j)
         << " for b_j^*\n";
      return false;
    }
    BKZ_BareissStep(work, j, prev);
  }
  return true;
}

// clang-format off
#endif  // SRC_LATT_BKZ_H_
// clang-format on
