// Copyright (C) 2026 Mathieu Dutour Sikiric <mathieu.dutour@gmail.com>
#ifndef SRC_LATT_LATTICEAUTOMORPHISMVINBERG_H_
#define SRC_LATT_LATTICEAUTOMORPHISMVINBERG_H_

// clang-format off
#include "MAT_Matrix.h"
#include "MAT_MatrixInt.h"
#include "LatticeRootSystem.h"
#include "LatticeRootDecomposition.h"
#include "LatticeStabEquiCan.h"
#include <utility>
#include <vector>
// clang-format on

#ifdef DEBUG
#define DEBUG_LATTICE_AUTOMORPHISM_VINBERG
#endif

#ifdef SANITY_CHECK
#define SANITY_CHECK_LATTICE_AUTOMORPHISM_VINBERG
#endif

/*
  The automorphism group of an even positive definite lattice through the
  Vinberg decomposition Aut(L) = W(R) rtimes Aut(L, rho):

    * W(R), the Weyl group of the root system, is not computed as a
      group; its order is read off the Dynkin type (LatticeRootSystem.h)
      and its generators are the reflections in the simple roots.
    * The residual Aut(L, rho), the stabiliser of a Weyl vector, is the
      automorphism group of the small family consisting of the simple
      roots and a characteristic family of the orthogonal complement
      R^perp: an integral form-preserving map that permutes the simple
      roots stabilises the fundamental chamber, hence fixes rho, and
      conversely. That family is far smaller than the full characteristic
      family of L, which is where the speedup comes from.

  The order is |W(R)| * |Aut(L, rho)| and the generators are the
  simple-root reflections together with the generators of Aut(L, rho);
  the huge factor W(R) is never enumerated.
 */

template <typename Tint> struct VinbergAutom {
  mpz_class order;                       // |Aut(L)| = |W(R)| * |Aut(L,rho)|
  mpz_class weyl_order;                  // |W(R)|
  mpz_class residual_order;             // |Aut(L, rho)|
  std::vector<MyMatrix<Tint>> ListGen;  // generators of Aut(L)
};

// The reflection in a root r, as an integral matrix acting on rows:
// s_r(x) = x - <x, r> r, with <r, r> = 2. As a matrix, g = I - (G r^T) r,
// integral since r and G are integral and <r,r> = 2 cancels the usual 2.
template <typename T, typename Tint>
MyMatrix<Tint> RootReflection(MyMatrix<T> const &GramMat,
                              MyVector<Tint> const &r) {
  int n = GramMat.rows();
  // w = G r^T (column), integral
  MyVector<Tint> w(n);
  for (int i = 0; i < n; i++) {
    T sum(0);
    for (int j = 0; j < n; j++) {
      sum += GramMat(i, j) * UniversalScalarConversion<T, Tint>(r(j));
    }
    w(i) = UniversalScalarConversion<Tint, T>(sum);
  }
  MyMatrix<Tint> g = IdentityMat<Tint>(n);
  for (int i = 0; i < n; i++) {
    for (int j = 0; j < n; j++) {
      g(i, j) -= w(i) * r(j);
    }
  }
  return g;
}

/*
  The residual family: the simple roots together with a characteristic
  family of R^perp lifted to the coordinates of L. Invariant under
  Aut(L, rho) and of full rank, but spanning only R (+) R^perp.
 */
template <typename T, typename Tint>
MyMatrix<Tint>
ResidualFamily(RootSystemData<Tint> const &rs,
               RootDecomposition<T, Tint> const &dec, std::ostream &os) {
  int n = rs.SimpleRoots.cols();
  std::vector<MyVector<Tint>> family;
  for (int i = 0; i < rs.SimpleRoots.rows(); i++) {
    family.push_back(GetMatrixRow(rs.SimpleRoots, i));
  }
  if (dec.PerpBasis.rows() > 0) {
    CanonicVectorFamily<Tint> perpFam =
        GetCanonicVectorFamily<T, Tint>(dec.PerpGram, os);
    MyMatrix<Tint> perpFull = perpFam.get_full();
    for (int i = 0; i < perpFull.rows(); i++) {
      MyVector<Tint> u = GetMatrixRow(perpFull, i);
      family.push_back(dec.PerpBasis.transpose() * u);
    }
  }
  return MatrixFromVectorFamilyDim(n, family);
}

// The order of the group generated by ListGen, from its permutation
// action on the family SHV (faithful, the family being of full rank).
template <typename Tint, typename Tgroup>
mpz_class OrderFromGens(MyMatrix<Tint> const &SHV,
                        std::vector<MyMatrix<Tint>> const &ListGen) {
  using Telt = typename Tgroup::Telt;
  using Tidx = typename Telt::Tidx;
  int n_row = SHV.rows();
  std::unordered_map<MyVector<Tint>, Tidx> MapRow;
  for (int i = 0; i < n_row; i++) {
    MapRow[GetMatrixRow(SHV, i)] = static_cast<Tidx>(i);
  }
  std::vector<Telt> ListPermGens;
  for (auto &eGen : ListGen) {
    MyMatrix<Tint> Mtr = eGen.transpose();
    std::vector<Tidx> ePerm(n_row);
    for (int i = 0; i < n_row; i++) {
      MyVector<Tint> v = Mtr * GetMatrixRow(SHV, i);
      auto iter = MapRow.find(v);
#ifdef SANITY_CHECK_LATTICE_AUTOMORPHISM_VINBERG
      if (iter == MapRow.end()) {
        std::cerr << "VINBERG: a generator does not permute the family\n";
        throw TerminalException{1};
      }
#endif
      ePerm[i] = iter->second;
    }
    ListPermGens.push_back(Telt(ePerm));
  }
  Tgroup grp(ListPermGens, n_row);
  return grp.size();
}

template <typename T, typename Tint, typename Tgroup>
VinbergAutom<Tint> ComputeAutomorphismVinberg(MyMatrix<T> const &GramMat,
                                              std::ostream &os) {
  int n = GramMat.rows();
  VinbergAutom<Tint> res;
  RootSystemData<Tint> rs = ComputeRootSystem<T, Tint>(GramMat, os);
  if (rs.n_roots == 0) {
    // Root free: no Weyl factor, Aut(L) is the residual itself. Fall back
    // to the ordinary automorphism computation on the full family.
    std::vector<MyMatrix<Tint>> gens =
        ArithmeticAutomorphismGroup<T, Tint, Tgroup>(GramMat, os);
    CanonicVectorFamily<Tint> fam = GetCanonicVectorFamily<T, Tint>(GramMat, os);
    res.weyl_order = mpz_class(1);
    res.residual_order = OrderFromGens<Tint, Tgroup>(fam.get_full(), gens);
    res.order = res.residual_order;
    res.ListGen = gens;
    return res;
  }
  res.weyl_order = WeylGroupOrder(rs);
  RootDecomposition<T, Tint> dec =
      ComputeRootDecomposition<T, Tint, Tgroup>(GramMat, os);
  MyMatrix<Tint> SHV = ResidualFamily<T, Tint>(rs, dec, os);
  std::vector<T> Vdiag(SHV.rows(), T(0));
  std::vector<MyMatrix<T>> ListMat{GramMat};
  // The automorphisms of the residual family = Aut(L, rho).
  std::vector<MyMatrix<Tint>> resGen =
      GetIntAutomorphism_ListMat_Vdiag<T, Tint, Tgroup>(SHV, ListMat, Vdiag,
                                                        os);
  res.residual_order = OrderFromGens<Tint, Tgroup>(SHV, resGen);
  res.order = res.weyl_order * res.residual_order;
  // Generators of Aut(L): the simple-root reflections (generating W(R))
  // and the residual generators.
  for (int i = 0; i < rs.SimpleRoots.rows(); i++) {
    res.ListGen.push_back(
        RootReflection<T, Tint>(GramMat, GetMatrixRow(rs.SimpleRoots, i)));
  }
  for (auto &g : resGen) {
    res.ListGen.push_back(g);
  }
#ifdef SANITY_CHECK_LATTICE_AUTOMORPHISM_VINBERG
  MyMatrix<Tint> G_int = UniversalMatrixConversion<Tint, T>(GramMat);
  for (auto &g : res.ListGen) {
    if (g * G_int * g.transpose() != G_int) {
      std::cerr << "VINBERG: a generator does not preserve the form\n";
      throw TerminalException{1};
    }
  }
#endif
  return res;
}

// clang-format off
#endif  // SRC_LATT_LATTICEAUTOMORPHISMVINBERG_H_
// clang-format on
