// Copyright (C) 2023 Mathieu Dutour Sikiric <mathieu.dutour@gmail.com>
#ifndef SRC_LATT_TSPACE_NAMELIST_H_
#define SRC_LATT_TSPACE_NAMELIST_H_

// clang-format off
#include "Namelist.h"
// clang-format on

SingleBlock SINGLEBLOCK_Get_Tspace_Description() {
  std::map<std::string, std::string> ListStringValues1_doc;
  std::map<std::string, std::string> ListBoolValues1_doc;
  std::map<std::string, std::string> ListIntValues1_doc;
  ListStringValues1_doc["TypeTspace"] = "The possible type of T-space\n\
InvGroup: The space of matrices invariant under a group\n   \
RealQuad: The space corresponding to a real quadratic field\n   \
ImagQuad: The space corresponding to a real quadratic field\n   \
Raw: the space given by matrices";
  ListIntValues1_doc["RealImagDim"] = "Default: 0\n\
The dimension d of the space GL_d(R) for R a number ring";
  ListIntValues1_doc["RealImagSum"] = "Default: 0\n\
The sum of the two roots of the polynomial. Only relevant for RealQuad and ImagQuad";
  ListIntValues1_doc["RealImagProd"] = "Default: 0\n\
The product of the two roots of the polynomial. Only relevant for RealQuad and ImagQuad";
  ListStringValues1_doc["ListGensInvGroup"] = "Default: unset\n\
The file containing the list of matrices describing the group\n\
It is used only if option InvGroup is selected";
  ListStringValues1_doc["SuperMatMethod"] = "Default: notneeded\n\
notneeded: For InvGroup, RealQuad, ImagQuad, the supermat is computed internally and so this option needs to be selected.\n\
Compute: Compute from the basis of the T-space\n\
File: Use matrix read from the file";
  ListStringValues1_doc["ListComm"] = "Default: unset\n\
unset: Then we do not need the file\n\
The file containing the list of matrices commuted to by the elements of GlStab";
  ListStringValues1_doc["PtGroupMethod"] = "Default: Trivial\n\
Trivial: Use the group of order 2 generated by -Id_n\n\
Compute: Compute the pointwise group stabilizer by using Plesken Souvignier with the vector configuration obtained by the supermat\n\
File: Use the pointwise stabilizer obtained from the file";
  ListStringValues1_doc["FilePtGroupGenerator"] = "Default: unset\n\
unset: If unset then the file is not needed\n\
The filename for the list of generators of the pointwise stabilizer";
  
  SingleBlock BlockTSPACE;
  BlockTSPACE.setListStringValues(ListStringValues1_doc);
  BlockTSPACE.setListBoolValues(ListBoolValues1_doc);
  BlockTSPACE.setListIntValues(ListIntValues1_doc);
  return BlockTSPACE;
}





// clang-format off
#endif  // SRC_LATT_TSPACE_NAMELIST_H_
// clang-format on
