name: CI(04B) cmake compilation of the code.

# https://help.github.com/en/articles/events-that-trigger-workflows#release-event-release
# model taken from https://github.com/mockersf/kmanb/releases
# on: release

on:
  # One time per month
  schedule:
    - cron: "0 0 4 2,4,6,8,10,12 *"
  # Manually triggered
  workflow_dispatch:
  # Disabled right now, when a push is made on master.
jobs:
  build-linux:
    timeout-minutes: 120  # 2 hours
    runs-on: ubuntu-latest
    env:
      GMP_INCDIR: /usr/include
      GMP_CXX_LINK: "-lm -lgmp -lgmpxx"
      BOOST_INCDIR: "/usr/include"
      BOOST_LINK: "/usr/lib/x86_64-linux-gnu/libboost_serialization.a"
      EIGEN_PATH: /home/runner/work/opt/eigen
      GLPK_INCLUDE: "-I/usr/include"
      GLPK_LINK: "-L/usr/lib -lglpk -Wl,-rpath,/usr/lib"
      CDDLIB_PATH: "/home/runner/work/opt/cddlib"
      CDDLIB_INCLUDE: "-I/home/runner/work/opt/cddlib/include/cddlib"
      CDDLIB_DOUBLE_LINK: "-L/home/runner/work/opt/cddlib/lib  -lcdd -Wl,-rpath,/home/runner/work/opt/cddlib/lib"
      CDDLIB_GMP_LINK: "-L/home/runner/work/opt/cddlib/lib  -lcddgmp -Wl,-rpath,/home/runner/work/opt/cddlib/lib"
      NAUTY_PATH: /home/runner/work/opt/nauty
      NAUTY_INCLUDE: "-I/home/runner/work/opt/nauty/include"
      NAUTY_LINK: "/home/runner/work/opt/nauty/lib/libnauty_static.a"
      LIBBLISS_PATH: /home/runner/opt/libbliss
      LIBBLISS_INCDIR: /home/runner/opt/libbliss/include
      LIBBLISS_LINK: "-L/home/runner/opt/libbliss/lib -lbliss -Wl,-rpath,/home/runner/opt/libbliss/lib"

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libgdbm-dev libsnappy-dev make pkg-config rlwrap software-properties-common zlib1g-dev
          sudo apt-get install -y wget g++ gcc cmake libgmp-dev libeigen3-dev autoconf autotools-dev libtool
          sudo apt-get install -y libboost-dev libboost-mpi-dev libboost-serialization-dev

      - name: Install Eigen
        run: |
          # We need specific version 3.3.9 because of a bug in 3.4.0 for algebraic data types.
          # wget -q https://gitlab.com/libeigen/eigen/-/archive/3.3.9/eigen-3.3.9.tar.gz
          # tar -xzf eigen-3.3.9.tar.gz
          # mkdir -p /home/runner/work/opt
          # cd eigen-3.3.9
          # mkdir build && cd build
          # cmake -DCMAKE_INSTALL_PREFIX=/home/runner/work/opt/eigen ..
          # make install
          # cd ../..
          # echo "After eigen-3.3.9 installation"

      - name: Build the code
        run: |
          ls
          echo "After ls"

          pwd
          echo "After pwd"

          mkdir build && cd build
          cmake -DCMAKE_PREFIX_PATH=/home/runner/work/opt/eigen ..
          make


