name: CI(10) Docker Image polyhedral_common

on:
  # One time per month
  schedule:
    - cron: "0 0 10 * *"
  # Manually triggered
  workflow_dispatch:
jobs:

  build:
    timeout-minutes: 150  # 2 hours
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build -t polyhedralcpp:build-env . --file docker_files/docker_compile/Dockerfile
