name: CI(16) of dual description using symmetries

# https://help.github.com/en/articles/events-that-trigger-workflows#release-event-release
# model taken from https://github.com/mockersf/kmanb/releases
# on: release

# Scheduling syntax is available at
# https://cloud.google.com/scheduler/docs/configuring/cron-job-schedules

on:
  # One time per month
  schedule:
    - cron: "0 0 16 * *"
  # Manually triggered
  workflow_dispatch:
  # Disabled right now, when a push is made on master.
jobs:
  build-linux:
    timeout-minutes: 120  # 2 hours
    runs-on: ubuntu-latest
    env:
      GMP_INCDIR: /usr/include
      GMP_CXX_LINK: "-lm -lgmp -lgmpxx"
      BOOST_INCDIR: "/usr/include"
      BOOST_LINK: "/usr/lib/x86_64-linux-gnu/libboost_serialization.a"
      EIGEN_PATH: /home/runner/work/opt/eigen
      NAUTY_PATH: /home/runner/work/opt/nauty
      NAUTY_INCLUDE: "-I/home/runner/work/opt/nauty/include"
      NAUTY_LINK: "/home/runner/work/opt/nauty/lib/libnauty_static.a"
      LIBBLISS_PATH: /home/runner/opt/libbliss
      LIBBLISS_INCDIR: /home/runner/opt/libbliss/include
      LIBBLISS_LINK: "-L/home/runner/opt/libbliss/lib -lbliss -Wl,-rpath,/home/runner/opt/libbliss/lib"

    steps:
      - uses: actions/checkout@v7
        with:
          submodules: recursive

      - uses: ./.github/actions/install-boost

      - uses: ./.github/actions/install-nauty
      - uses: ./.github/actions/install-bliss
      - uses: ./.github/actions/install-eigen
      - uses: ./.github/actions/install-gap

      - name: Test dual description using symmetries
        run: |
          make -C src_dualdesc -f Makefile_serial_dualdesc
          echo "After compilation of dual desc code"

          cd CI_tests/16_EquivDualDesc
          ../../gap.sh < TestCases.g
          if [ ! -f "CI_CONCLUSION" ]; then
            echo "gap test code has not finished correctly" >&2
            exit 1
          fi
          cd ../..
          echo "We are in test directory"
