name: Docker Image polyhedral_common CI

on:
  # At 2PM on every Monday
  schedule:
    - cron: "0 0 2 * *"
  # Manually triggered
  workflow_dispatch:
jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build -t polyhedralcpp:build-env . --file script_docker/Dockerfile
