name: Docker Image polyhedral_common CI

on:
  # Every day at 5 am.
  schedule:
    - cron: "0 14 * * 1"
  # Manually triggered
  workflow_dispatch:
jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build -t polyhedralcpp:build-env . --file script_docker/Dockerfile
