name: release-flow

# https://help.github.com/en/articles/events-that-trigger-workflows#release-event-release
# model taken from https://github.com/mockersf/kmanb/releases
# on: release

on:
  push:
    branches:
    - master

jobs:
  build-linux:
    runs-on: ubuntu-latest
    env:
      GMP_INCDIR: /usr/include
      GMP_CXX_LINK: "-lm -lgmp -lgmpxx"
      BOOST_INCDIR: "/usr/include"
      BOOST_LINK: "-lboost_serialization"
      EIGEN_PATH: /opt/eigen
      TBB_INCDIR: /usr/include
      TBB_LINK: "-ltbb"
      GSL_INCDIR: /usr/include
      GSL_C_LINK: "-lgsl -lgslcblas"
      GLPK_INCLUDE: "-I/usr/include"
      GLPK_LINK: "-L/usr/lib -lglpk -Wl,-rpath,/usr/lib"
      FLINT_INCDIR: "/include"
      FLINT_LINK: "-lflint"
      CDDLIB_INCLUDE: "-I/opt/cddlib/include/cddlib"
      CDDLIB_DOUBLE_LINK: "-L/opt/cddlib/lib  -lcdd -Wl,-rpath,/opt/cddlib/lib"
      CDDLIB_GMP_LINK: "-L/opt/cddlib/lib  -lcddgmp -Wl,-rpath,/opt/cddlib/lib"
      NETCDF_CXX_ALLINC: "-I/opt/netcdf-cxx4-4.3.1/include -I/opt/netcdf-cxx4-4.3.1/include"
      NETCDF_CXX_LINK: "-L/opt/netcdf-cxx4-4.3.1/lib -lnetcdf_c++4 -Wl,-rpath,/opt/netcdf-cxx4-4.3.1/lib"
      NAUTY_PATH: /opt/nauty
      NAUTY_INCLUDE: "-I/opt/nauty/include"
      NAUTY_LINK: "-L/opt/nauty/lib -lnauty -Wl,-rpath,/opt/nauty/lib"

    steps:
      - name: Get the version
        id: get_version
        run: echo ::set-output name=VERSION::${GITHUB_REF#refs/tags/}
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      - name: Install Dependencies
        run: |
          sudo apt-get install -y libgdbm-dev libsnappy-dev make pkg-config rlwrap software-properties-common zlib1g-dev
          sudo apt-get install -y wget
          sudo apt-get install -y g++-11 clang-12
          sudo apt-get install -y g++ gcc gfortran
          sudo apt-get install -y cmake
          sudo apt-get install -y libgmp-dev
          sudo apt-get install -y libboost-dev libboost-mpi-dev libboost-serialization-dev
          sudo apt-get install -y libtbb-dev libgsl-dev libglpk-dev libflint-dev
          sudo apt-get install -y autoconf autotools-dev libtool
          sudo apt-get install -y texlive-latex-base # needed for the CDD manual to be compiled
          sudo apt-get install -y libcurl4-gnutls-dev
          sudo apt-get install -y libntl-dev libmpfr-dev
          sudo apt-get install -y openmpi-bin libopenmpi-dev

      - name: Build and release
        run: |
          ls
          cd basic_common_cpp/ExternalLib/nauty && mkdir build
          cd basic_common_cpp/ExternalLib/nauty/build && cmake -DCMAKE_INSTALL_PREFIX:PATH=$NAUTY_PATH .. && make all install
          cd src_lorenzian && make && strip LORENTZ_FundDomain_AllcockEdgewalk
      - uses: papeloto/action-zip@v1
        with:
          files: target/release/LORENTZ_FundDomain_AllcockEdgewalk
          dest: LORENTZ_FundDomain_AllcockEdgewalk-linux.zip
      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: LORENTZ_FundDomain_AllcockEdgewalk-linux.zip
          asset_name: LORENTZ_FundDomain_AllcockEdgewalk-linux-$VERSION.zip
          tag: ${{ github.ref }}
          overwrite: true
